[workspace]

[package]
name = "pdf-font-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.pdf-font]
path = ".."
default-features = false
features = ["std"]

[[bin]]
name = "parse_cff"
path = "fuzz_targets/parse_cff.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_cmap"
path = "fuzz_targets/parse_cmap.rs"
test = false
doc = false
bench = false
