[workspace]

[package]
name = "lopdf-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.lopdf]
path = ".."
default-features = false
features = []

[[bin]]
name = "parse_document"
path = "fuzz_targets/parse_document.rs"
test = false
doc = false
bench = false
