"""Type stubs for pdfengine."""

from __future__ import annotations

from typing import Iterator, Optional, Union

def open_pdf(path: str, password: Optional[str] = None) -> "Document":
    """Open a PDF from a file path, returning a Document."""
    ...

def merge_pdfs(input_paths: list[str], output_path: str) -> None:
    """Merge multiple PDF files into a single output file."""
    ...

def validate_pdfa(path: str) -> "ComplianceReport":
    """Validate a PDF file against PDF/A conformance requirements."""
    ...

def decrypt_pdf(input_path: str, output_path: str, password: str) -> None:
    """Decrypt a password-protected PDF and write the decrypted copy to a file."""
    ...

class Document:
    """A PDF document.

    Open from a file path or raw bytes. Supports context manager protocol.
    """

    def __init__(
        self, source: Union[str, bytes], password: Optional[str] = None
    ) -> None: ...
    @property
    def page_count(self) -> int: ...
    @property
    def metadata(self) -> DocumentInfo: ...
    @property
    def bookmarks(self) -> list[Bookmark]: ...
    def __getitem__(self, index: int) -> Page: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Page]: ...
    def __enter__(self) -> Document: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...
    def render_all(self, dpi: float = 150.0) -> list[RenderedImage]: ...
    def search(self, query: str) -> list[int]: ...
    def extract_text(self, page_num: int) -> str: ...
    def save(self, path: str) -> None: ...
    def get_form_fields(self) -> list[FormField]: ...
    def set_form_field(self, name: str, value: str) -> bool: ...
    def get_annotations(self, page: int) -> list[Annotation]: ...
    def add_annotation(
        self,
        page: int,
        annot_type: str,
        rect: tuple[float, float, float, float],
        content: Optional[str] = None,
    ) -> None: ...
    def redact_text(self, search_term: str, page: Optional[int] = None) -> RedactReport: ...
    def encrypt(
        self, output_path: str, password: str, owner_password: Optional[str] = None
    ) -> None: ...
    def decrypt(self, output_path: str, password: str) -> None: ...
    def __repr__(self) -> str: ...

class Page:
    """A single page in a PDF document."""

    @property
    def index(self) -> int: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def rotation(self) -> int: ...
    @property
    def geometry(self) -> PageGeometry: ...
    def render(
        self,
        dpi: float = 150.0,
        width: Optional[int] = None,
        height: Optional[int] = None,
        background: Optional[tuple[float, float, float, float]] = None,
    ) -> RenderedImage: ...
    def thumbnail(self, max_dimension: int = 256) -> RenderedImage: ...
    def extract_text(self) -> str: ...
    def extract_text_blocks(self) -> list[TextBlock]: ...
    def __repr__(self) -> str: ...

class RenderedImage:
    """A rendered page as RGBA pixel data."""

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def pixels(self) -> bytes: ...
    def to_pil(self) -> "PIL.Image.Image": ...
    def to_numpy(self) -> "numpy.ndarray": ...
    def save(self, path: str) -> None: ...
    def __repr__(self) -> str: ...

class TextBlock:
    """A block of text from a page."""

    @property
    def text(self) -> str: ...
    @property
    def spans(self) -> list[TextSpan]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TextSpan:
    """A single text span at a specific position."""

    @property
    def text(self) -> str: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def font_size(self) -> float: ...
    def __repr__(self) -> str: ...

class DocumentInfo:
    """Document metadata."""

    @property
    def title(self) -> Optional[str]: ...
    @property
    def author(self) -> Optional[str]: ...
    @property
    def subject(self) -> Optional[str]: ...
    @property
    def keywords(self) -> Optional[str]: ...
    @property
    def creator(self) -> Optional[str]: ...
    @property
    def producer(self) -> Optional[str]: ...
    def __repr__(self) -> str: ...

class Bookmark:
    """A bookmark (outline item) in the document."""

    @property
    def title(self) -> str: ...
    @property
    def page(self) -> Optional[int]: ...
    @property
    def children(self) -> list[Bookmark]: ...
    def __repr__(self) -> str: ...

class PageGeometry:
    """Full page geometry (boxes, rotation)."""

    @property
    def media_box(self) -> tuple[float, float, float, float]: ...
    @property
    def crop_box(self) -> tuple[float, float, float, float]: ...
    @property
    def rotation(self) -> int: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def pixel_dimensions(self, dpi: float) -> tuple[int, int]: ...
    def __repr__(self) -> str: ...

class ComplianceIssue:
    """A single compliance issue found during PDF/A validation."""

    @property
    def rule(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def location(self) -> Optional[str]: ...
    def __repr__(self) -> str: ...

class ComplianceReport:
    """Result of a PDF/A compliance validation."""

    @property
    def is_compliant(self) -> bool: ...
    @property
    def error_count(self) -> int: ...
    @property
    def warning_count(self) -> int: ...
    @property
    def issues(self) -> list[ComplianceIssue]: ...
    @property
    def pdfa_level(self) -> Optional[str]: ...
    def __repr__(self) -> str: ...

class FormField:
    """An interactive form field (AcroForm widget)."""

    @property
    def name(self) -> str: ...
    @property
    def field_type(self) -> str: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def page(self) -> Optional[int]: ...
    def __repr__(self) -> str: ...

class Annotation:
    """A PDF annotation (highlight, freetext, etc.)."""

    @property
    def page(self) -> int: ...
    @property
    def annot_type(self) -> str: ...
    @property
    def rect(self) -> tuple[float, float, float, float]: ...
    @property
    def contents(self) -> Optional[str]: ...
    @property
    def author(self) -> Optional[str]: ...
    def __repr__(self) -> str: ...

class RedactReport:
    """Result of a search-and-redact operation."""

    @property
    def matches_found(self) -> int: ...
    @property
    def areas_redacted(self) -> int: ...
    @property
    def pages_affected(self) -> int: ...
    def __repr__(self) -> str: ...
