[package]
name = "pdf-forms"
version = "1.0.0-beta.1"
edition = "2021"
license = "MIT"
description = "AcroForm engine for PDF interactive forms."

[dependencies]
pdf-syntax = { path = "../pdf-syntax" }
thiserror = { workspace = true }
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lopdf = { path = "../lopdf" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
lopdf = { path = "../lopdf", default-features = false, features = ["wasm_js"] }

[dev-dependencies]
