//! Generate the fixture the Java binding tests read.
//!
//! `crates/pdf-java/src/test/resources/sample.pdf` used to be a LiveCycle form
//! from a corpus we hold but have no right to redistribute, in a tree that is
//! going public (#310). Nothing in `PdfDocumentTest` needs a form: it opens the
//! file, asks for a page count above zero, wants non-blank text on page 0, wants
//! Producer or Creator to be set, and wants `validatePdfA` to return a report.
//! A one-page document with a line of text answers all five.
//!
//! # Why this is a program and not a committed blob
//!
//! The file IS committed -- `mvn test` has to keep working without a Rust step
//! having run first. This program is what gives it provenance, and
//! `scripts/ci/the_java_fixture_is_the_one_we_generate.py` runs it and compares
//! byte for byte, so the file and the code that explains it cannot drift apart.
//!
//! # Determinism
//!
//! Every field a PDF writer normally fills from the clock or from entropy is
//! pinned here: `/CreationDate`, `/ModDate` and both halves of `/ID`. They are
//! not normalised away at comparison time on purpose -- the bytes most likely
//! to drift are exactly the ones a lenient comparison stops reading.

// Copyright (c) 2026 Innovation Trigger B.V.
//
// PDFluent is available under two licences, at your option: the GNU AGPLv3, or
// the PDFluent Commercial Licence. See the LICENSE file in this repository --
// that file travels with the copy you received, which a URL does not.
use lopdf::{dictionary, Document, Object, Stream};
use std::{env, fs, path::PathBuf};

/// Fixed so two runs produce the same bytes. Any date would do; this is the day
/// the fixture replaced the corpus file.
const DATUM: &str = "D:20260902000000Z";
/// Fixed for the same reason. A real writer derives `/ID` from the clock and the
/// file's contents, which is exactly what must not happen here.
const ID: &[u8] = b"pdfluent-java-binding-fixture-001";

fn main() {
    let out: PathBuf = env::args().nth(1).map(PathBuf::from).unwrap_or_else(|| {
        eprintln!("usage: java_binding_fixture <output.pdf>");
        std::process::exit(2);
    });

    let mut doc = Document::with_version("1.7");
    let pages_id = doc.new_object_id();

    let font_id = doc.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "Type1",
        "BaseFont" => "Helvetica",
        "Encoding" => "WinAnsiEncoding",
    });

    // The text has to survive extraction, because `testExtractText` asserts the
    // page is not blank. Base-14 Helvetica with WinAnsiEncoding needs no
    // embedded program and no ToUnicode: every code here is its own character.
    let content = Stream::new(
        dictionary! {},
        b"BT /F1 24 Tf 72 700 Td (PDFluent Java binding fixture) Tj ET\n\
          BT /F1 12 Tf 72 660 Td (Generated by pdf-manip/examples/java_binding_fixture.rs) Tj ET\n\
          BT /F1 12 Tf 72 640 Td (This file is generated. Do not edit it by hand.) Tj ET"
            .to_vec(),
    );
    let content_id = doc.add_object(Object::Stream(content));

    let mut fonts = lopdf::Dictionary::new();
    fonts.set("F1", Object::Reference(font_id));
    let mut resources = lopdf::Dictionary::new();
    resources.set("Font", Object::Dictionary(fonts));

    let page_id = doc.add_object(dictionary! {
        "Type" => "Page",
        "Parent" => Object::Reference(pages_id),
        "MediaBox" => Object::Array(vec![
            Object::Integer(0), Object::Integer(0),
            Object::Integer(595), Object::Integer(842),
        ]),
        "Contents" => Object::Reference(content_id),
        "Resources" => Object::Dictionary(resources),
    });

    doc.objects.insert(
        pages_id,
        Object::Dictionary(dictionary! {
            "Type" => "Pages",
            "Kids" => Object::Array(vec![Object::Reference(page_id)]),
            "Count" => Object::Integer(1),
        }),
    );

    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => Object::Reference(pages_id),
    });

    // `testMetadata` wants Producer or Creator. Both are set, so the assertion
    // cannot pass on an accident of one of them.
    let info_id = doc.add_object(dictionary! {
        "Producer" => Object::string_literal("PDFluent"),
        "Creator" => Object::string_literal("pdf-manip/examples/java_binding_fixture.rs"),
        "Title" => Object::string_literal("PDFluent Java binding fixture"),
        "CreationDate" => Object::string_literal(DATUM),
        "ModDate" => Object::string_literal(DATUM),
    });

    doc.trailer.set("Root", Object::Reference(catalog_id));
    doc.trailer.set("Info", Object::Reference(info_id));
    doc.trailer.set(
        "ID",
        Object::Array(vec![
            Object::String(ID.to_vec(), lopdf::StringFormat::Hexadecimal),
            Object::String(ID.to_vec(), lopdf::StringFormat::Hexadecimal),
        ]),
    );

    let mut buf = Vec::new();
    doc.save_to(&mut buf)
        .expect("the generated document must save");
    fs::write(&out, &buf).unwrap_or_else(|e| panic!("could not write {}: {e}", out.display()));
    println!("wrote {} ({} bytes)", out.display(), buf.len());
}
