#!/usr/bin/env bash
# Rewrite the wasm-pack-emitted package.json so it carries the npm
# release identity for @pdfluent/xfa-wasm.
#
# wasm-pack copies fields from Cargo.toml verbatim. The crate is called
# `xfa-wasm` (no `@scope/` allowed in Rust crate names) and the workspace
# repository field used to point at the private GitLab monorepo (a dead link
# for a public npm reader). None of those are correct for the published npm
# package, so this script rewrites them after wasm-pack.
#
# Reciprocal backlink to github.com/pdfluent/pdfluent (source-available
# mirror, for SEO/GEO): only written when WASM_REPO_PUBLIC=1 is set. That repo
# is NOT public yet (Phase 0.5 dependency) — a link to a private repo 404s and
# actively hurts SEO/GEO, so the field is omitted by default. Set
# WASM_REPO_PUBLIC=1 only after confirming github.com/pdfluent/pdfluent is live.
#
# Usage:
#   ./scripts/release/transform-wasm-pkg.sh <pkg-dir> <target-version>
#   WASM_REPO_PUBLIC=1 ./scripts/release/transform-wasm-pkg.sh <pkg-dir> <target-version>
#
# Exits non-zero if any required field is missing or wrong after rewrite.

set -euo pipefail

PKG_DIR="${1:?usage: $0 <pkg-dir> <target-version>}"
VERSION="${2:?usage: $0 <pkg-dir> <target-version>}"

PKG_JSON="$PKG_DIR/package.json"

if [[ ! -f "$PKG_JSON" ]]; then
    echo "error: $PKG_JSON not found" >&2
    exit 2
fi

python3 - "$PKG_JSON" "$VERSION" <<'PY'
import json, os, sys, pathlib

pkg_path = pathlib.Path(sys.argv[1])
version  = sys.argv[2]

d = json.loads(pkg_path.read_text(encoding="utf-8"))

# Identity
d["name"]    = "@pdfluent/sdk-wasm"
d["version"] = version
d["license"] = "SEE LICENSE IN LICENSE"
d["homepage"] = "https://pdfluent.com"
d["description"] = "PDFluent browser SDK — read, edit, annotate, redact, sign, and validate PDFs (including XFA) entirely client-side via WASM."
d["author"] = "Innovation Trigger BV <team@pdfluent.com>"

# Reciprocal repository backlink — gated on WASM_REPO_PUBLIC=1 (see header).
if os.environ.get("WASM_REPO_PUBLIC") == "1":
    d["repository"] = {"type": "git", "url": "https://github.com/pdfluent/pdfluent"}
else:
    d.pop("repository", None)
    print("note: repository field omitted (set WASM_REPO_PUBLIC=1 once "
          "github.com/pdfluent/pdfluent is confirmed public)", file=sys.stderr)
d.pop("bugs", None)

# Cleaner keyword set
d["keywords"] = ["pdf", "wasm", "pdfluent", "browser", "sdk", "xfa", "forms", "annotate", "redact"]

# `files:` array — wasm-pack defaults to ["<crate>_bg.wasm", "<crate>.js",
# "<crate>.d.ts"] which OMITS the `snippets/` directory. xfa_wasm.js line 2
# imports from `./snippets/xfa-wasm-<hash>/inline0.js` (generated by
# `#[wasm_bindgen(inline_js = …)]`). Without `snippets/` in the published
# tarball, every consumer hits `ERR_MODULE_NOT_FOUND` on first import —
# caught by the matched-runtime Node smoke. Add `snippets` so npm pack
# picks the directory up; also include the wasm typings sidecar.
import pathlib as _pl
pkg_dir = _pl.Path(sys.argv[1]).parent
existing_files = d.get("files") or []
if (pkg_dir / "snippets").is_dir() and "snippets" not in existing_files:
    existing_files.append("snippets")
for extra in ("xfa_wasm_bg.wasm.d.ts",):
    if (pkg_dir / extra).is_file() and extra not in existing_files:
        existing_files.append(extra)
d["files"] = existing_files

pkg_path.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(json.dumps({k: d.get(k) for k in ("name", "version", "license", "homepage", "author", "files")}, indent=2))
PY

# Verify expected fields are present and absent
ok=1
required='"@pdfluent/sdk-wasm" '"$VERSION"' SEE LICENSE IN LICENSE pdfluent.com'
for s in "@pdfluent/sdk-wasm" "$VERSION" "SEE LICENSE IN LICENSE" "https://pdfluent.com"; do
    if ! grep -q -F "$s" "$PKG_JSON"; then
        echo "  MISSING: $s" >&2
        ok=0
    fi
done
forbidden_list=("/Users/" "/home/")
if [[ "${WASM_REPO_PUBLIC:-}" != "1" ]]; then
    forbidden_list+=("github.com")
elif ! grep -q -F "github.com/pdfluent/pdfluent" "$PKG_JSON"; then
    echo "  WASM_REPO_PUBLIC=1 set but repository field is missing/wrong" >&2
    ok=0
fi
for forbidden in "${forbidden_list[@]}"; do
    if grep -q -F "$forbidden" "$PKG_JSON"; then
        echo "  FORBIDDEN (must not appear): $forbidden" >&2
        ok=0
    fi
done
# LICENSE file must be the PDFluent Commercial License
LIC="$PKG_DIR/LICENSE"
if ! grep -q "PDFluent Commercial License" "$LIC" 2>/dev/null; then
    echo "  LICENSE missing or not PDFluent Commercial License: $LIC" >&2
    ok=0
fi

if [[ $ok -ne 1 ]]; then
    echo "transform-wasm-pkg.sh: audit FAILED" >&2
    exit 3
fi

echo "transform-wasm-pkg.sh: audit PASS"
