[package]
name = "pdf-compliance"
version = "1.0.0-beta.1"
edition = "2021"
license = "MIT"
description = "PDF compliance checking (PDF/A, PDF/UA)."

[dependencies]
pdf-syntax = { path = "../pdf-syntax" }
lopdf.workspace = true
thiserror = "2"
log = "0.4"
cff-parser.workspace = true
ttf-parser.workspace = true
