[package]
name = "pdf-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
pdf-syntax = { path = "../pdf-syntax", features = ["std", "images"], version = "=0.5.0" }
pdf-engine = { path = "../pdf-engine", version = "=1.0.0-beta.1" }
pdf-compliance = { path = "../pdf-compliance", version = "=1.0.0-beta.1" }
pdf-extract = { path = "../pdf-extract", version = "=1.0.0-beta.1" }
pdf-manip = { path = "../pdf-manip", version = "=1.0.0-beta.1" }
pdf-forms = { path = "../pdf-forms", version = "=1.0.0-beta.1" }
pdf-xfa.workspace = true
xfa-dom-resolver.workspace = true
formcalc-interpreter.workspace = true
xfa-layout-engine.workspace = true
lopdf.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "pdf_parse"
harness = false

[[bench]]
name = "xfa_operations"
harness = false

[[bench]]
name = "sdk_operations"
harness = false

[[bench]]
name = "pdf_benchmarks"
harness = false

