// Copyright (c) 2026 Innovation Trigger B.V. All rights reserved.
//
// This software is proprietary. The PDFluent application is free to use,
// including for commercial purposes. Redistribution, or extraction or reuse
// of its components (including the embedded PDF engine), requires a licence.
// See https://pdfluent.com/license for terms.

//! The dynamic-XFA fixture keeps paginating, and stays ours (#259).
//!
//! The editor's only dynamic-XFA coverage -- page counts, form-model
//! enumeration, fill persistence, the commit loop -- ran against a third-party
//! immigration form. Its redistribution terms were never established, so the
//! file was purged from history and the four tests went with it, because
//! `include_bytes!` resolves at build time.
//!
//! `fixtures/xfa-layout/xl_31_dynamic_multipage_overflow.pdf` is the
//! replacement, generated by
//! `crates/xfa-test-runner/examples/generate_xfa_layout_fixtures.rs` and
//! therefore ours to publish.
//!
//! WHY THIS TEST EXISTS RATHER THAN JUST THE FIXTURE
//!
//! The property the editor's tests depend on is not visible in the file. A
//! one-page shell that flattens to three pages looks, on disk, exactly like a
//! one-page shell that flattens to one -- and the thirty fixtures generated
//! before this one all do the second thing while looking like they should do
//! the first. Nothing asserted anything about any of them, which is why the
//! issue had to establish it by hand.
//!
//! So a layout change that quietly returned this fixture to a single page would
//! break the editor's tests in another repository with no local signal at all.
//! This is that signal.

use std::path::PathBuf;

/// 46..60 fields all flatten to three pages; the fixture carries 50, in the
/// middle of that band. Pinned exactly: "more than one" would still pass if
/// pagination collapsed from three pages to two, and two is a different
/// document from the one the editor's assertions were written against.
const EXPECTED_FLATTENED_PAGES: usize = 3;

/// The shell reports one page. That gap -- one on disk, three when laid out --
/// is the entire behaviour under test.
const EXPECTED_SHELL_PAGES: usize = 1;

/// A fixture that lost its fields would still flatten to some number of pages
/// and would still look fine here. The editor enumerates these.
const EXPECTED_FIELD_COUNT: usize = 50;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("fixtures/xfa-layout/xl_31_dynamic_multipage_overflow.pdf")
}

fn page_count(pdf: &[u8]) -> usize {
    lopdf::Document::load_mem(pdf)
        .expect("flattened output must parse")
        .page_iter()
        .count()
}

#[test]
fn dynamic_xfa_fixture_shell_is_one_page_and_flattens_to_three() {
    let path = fixture_path();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "{}: {e}. Regenerate with: cargo run -p xfa-test-runner \
             --example generate_xfa_layout_fixtures",
            path.display()
        )
    });

    assert_eq!(
        page_count(&bytes),
        EXPECTED_SHELL_PAGES,
        "the shell PDF must report one page; the whole point is that the \
         rendered count differs from it"
    );

    let (flattened, _meta) =
        pdf_xfa::flatten_xfa_to_pdf_with_metadata(&bytes).expect("fixture must flatten");
    let pages = page_count(&flattened);

    assert_eq!(
        pages, EXPECTED_FLATTENED_PAGES,
        "the dynamic XFA layout must still paginate to {EXPECTED_FLATTENED_PAGES} \
         pages (got {pages}). If this dropped to 1, pagination regressed and the \
         editor's dynamic-XFA tests are now asserting nothing; if it merely \
         shifted, re-measure with `cargo run -p pdf-xfa --example flatten_xfa` \
         and move the constant deliberately."
    );
    assert!(
        pages > EXPECTED_SHELL_PAGES,
        "rendered pages ({pages}) must exceed the shell's {EXPECTED_SHELL_PAGES}"
    );
}

#[test]
fn dynamic_xfa_fixture_fields_are_bound_to_data() {
    let bytes = std::fs::read(fixture_path()).expect("fixture must exist");
    let text = String::from_utf8_lossy(&bytes);

    // The editor's fill and commit tests select on `!bind_none`, which is false
    // for any field that does not carry `<bind match="none"/>`. A fixture that
    // grew one would silently leave those tests without a candidate field.
    assert!(
        !text.contains(r#"match="none""#),
        "no field may opt out of data binding: the editor's fill tests need a \
         datasets-bound text field to write into"
    );
    assert!(
        text.contains("xfa:datasets"),
        "the fixture must carry a datasets packet, or a filled value has \
         nowhere to persist across save/reopen"
    );

    let fields = text.matches("<field name=\"item").count();
    assert_eq!(
        fields, EXPECTED_FIELD_COUNT,
        "expected {EXPECTED_FIELD_COUNT} data-bound fields, found {fields}. The \
         field count sets the page count; changing it without re-measuring \
         breaks the assertion above for an unrelated reason."
    );
}
