#!/usr/bin/env python3
# Copyright (c) 2026 Innovation Trigger B.V.
#
# PDFluent is available under two licences, at your option: the GNU AGPLv3, or
# the PDFluent Commercial Licence. See the LICENSE file in this repository --
# that file travels with the copy you received, which a URL does not.
"""A published measurement names the run it came from, or it does not go out.

WHY THIS EXISTS

The claim register opens with the rule: a number without an ID does not leave
the building. It was written because numbers wander. They get copied from a
strategy document to a landing page to an email, and after three copies nobody
can say where they came from -- A08, A09 and A10 are all still sitting in the
register as `NEEDS-SOURCE` for exactly that reason, and A11 was published,
believed for six weeks and then withdrawn because the build it was measured on
damaged content in a way that made the number go UP.

The rule was enforced by a person reading a table. This is the mechanical half,
inside the repository where the measuring happens: the benchmark programme
writes a run file per measurement, and the document that publishes those numbers
may carry no figure that does not resolve to one.

WHAT IT CHECKS

  1. Every run file in benchmarks/runs/v7/ is a run: its identifier is its
     filename, its date is a real date and not in the future, its machine class
     has an entry in benchmarks/BASELINE_HARDWARE.toml, and it carries all three
     axes.

  2. An axis that measured nothing publishes nothing. `"status": "skipped"`
     must carry a reason and may carry no figures -- an axis that reports a
     number it did not measure is worse than a gap, because a gap is legible.

  3. The measured table in the published document is what the run files say.
     It is generated by `scripts/benchmarks/v7_benchmark.py publish`; this guard
     regenerates it and compares. A figure edited by hand, a figure that outlived
     the run it names, a run file deleted from under a published number -- all
     three come out as a difference.

  4. Outside that table, the published document carries no measurement. A
     figure in the prose is a figure with no run behind it. There is one way to
     write a number that is not a measurement -- a threshold, marked
     `(threshold)` on the line -- and it is deliberately ugly so it stays rare.

  5. Every run identifier mentioned anywhere under benchmarks/ resolves to a
     run file. A citation to a run that does not exist is the same defect from
     the other end.

# FLOOR: run files >= 1 and published rows >= 3 -- a guard with nothing to
# check reports green. The first version of this file passed on an empty
# directory, which is the same green a correct tree gives and means the
# opposite.

Exit codes:
  0  every published figure resolves to a run that measured it
  1  it does not
"""

from __future__ import annotations

import argparse
import datetime as dt
import importlib.util
import json
import pathlib
import re
import sys
import tomllib

MIN_RUNS = 1
MIN_ROWS = 3

# A measurement in prose: a number wearing a unit, or a count of documents.
# `PDF/A-2b`, `Apache-2.0` and `veraPDF 1.28.2` are not measurements and do not
# match; `98.0%`, `1.7 ms` and `288 of 300 documents` are.
MEASUREMENT = re.compile(
    r"(?<![\w.-])\d+(?:[.,]\d+)?\s*(?:%|ms|s\b|KB|MB|GB)"
    r"|(?<![\w.-])\d+\s+(?:of|van)\s+\d+\s+document",
    re.IGNORECASE,
)

# The escape hatch of rule 4, spelled out so it can be grepped for.
THRESHOLD = "(threshold)"

RUN_MENTION = re.compile(r"v7-\d{4}-\d{2}-\d{2}-[a-z0-9][a-z0-9-]*")

# Keys an axis may carry while reporting that it measured nothing. Anything else
# on a skipped axis is a figure without a measurement behind it.
SKIPPED_KEYS = {"status", "why"}


def load_programme(repo: pathlib.Path):
    """Import the benchmark programme from the tree under test.

    From the tree, not from this guard's own directory: the test drives both
    over temporary repositories, and a guard that reached back into the real
    checkout would report on a tree nobody asked it about.
    """
    path = repo / "scripts" / "benchmarks" / "v7_benchmark.py"
    if not path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("v7_benchmark_under_test", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def markdown_files(repo: pathlib.Path) -> list[pathlib.Path]:
    directory = repo / "benchmarks"
    return sorted(p for p in directory.rglob("*.md")) if directory.is_dir() else []


def check_run(path: pathlib.Path, run: dict, classes: set[str],
              axes: tuple[str, ...], today: dt.date) -> list[str]:
    problems = []
    name = path.name
    if run.get("run_id") != path.stem:
        problems.append(f"{name}: says its run is {run.get('run_id')!r}; a run "
                        f"whose file and identifier disagree cannot be cited by "
                        f"either")
    try:
        when = dt.date.fromisoformat(run.get("date", ""))
    except ValueError:
        problems.append(f"{name}: {run.get('date')!r} is not a date")
    else:
        if when > today:
            problems.append(f"{name}: dated {when}, which is in the future -- "
                            f"nobody measured on it")
    machine = run.get("machine_class")
    if machine not in classes:
        problems.append(f"{name}: machine class {machine!r} has no entry in "
                        f"benchmarks/BASELINE_HARDWARE.toml, so the numbers "
                        f"belong to a machine nobody described (#283)")
    if not re.fullmatch(r"[0-9a-f]{40}", run.get("commit", "")):
        problems.append(f"{name}: names no commit, so what was measured cannot "
                        f"be checked out again")
    given = run.get("axes", {})
    missing = [axis for axis in axes if axis not in given]
    if missing:
        problems.append(f"{name}: no {', '.join(missing)} axis. All three are "
                        f"reported together or the run says nothing about the "
                        f"trade between them")
    for axis_name, axis in given.items():
        status = axis.get("status")
        if status not in ("measured", "skipped"):
            problems.append(f"{name}: axis {axis_name} has status {status!r}")
            continue
        if status == "skipped":
            if not axis.get("why"):
                problems.append(f"{name}: axis {axis_name} was skipped without "
                                f"saying why")
            extra = sorted(set(axis) - SKIPPED_KEYS)
            if extra:
                problems.append(f"{name}: axis {axis_name} measured nothing and "
                                f"still reports {', '.join(extra)}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", default=str(pathlib.Path(__file__).resolve().parents[2]))
    parser.add_argument("--today", default=dt.date.today().isoformat(),
                        help="the day this runs on; the test pins it")
    args = parser.parse_args()
    repo = pathlib.Path(args.repo).resolve()
    today = dt.date.fromisoformat(args.today)

    programme = load_programme(repo)
    if programme is None:
        print("FAIL: scripts/benchmarks/v7_benchmark.py is not there. Every "
              "published figure is resolved through it; without it nothing "
              "below can be checked.", file=sys.stderr)
        return 1

    problems: list[str] = []

    registry = repo / programme.REGISTRY
    classes: set[str] = set()
    if registry.is_file():
        classes = set(tomllib.loads(registry.read_text()).get("classes", {}))
    else:
        problems.append(f"{programme.REGISTRY} is missing; no run can name a "
                        f"machine that is written down")

    run_dir = repo / programme.RUNS_DIR
    run_files = sorted(run_dir.glob("*.json")) if run_dir.is_dir() else []
    runs = []
    for path in run_files:
        try:
            run = json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            problems.append(f"{path.name}: is not readable JSON ({exc})")
            continue
        problems += check_run(path, run, classes, programme.AXES, today)
        runs.append(run)

    if len(runs) < MIN_RUNS:
        problems.append(f"{len(runs)} run file(s) in {programme.RUNS_DIR}, floor "
                        f"is {MIN_RUNS}. A guard with nothing to check reports "
                        f"the same green as a correct tree")

    published = repo / programme.PUBLISHED
    if not published.is_file():
        problems.append(f"{programme.PUBLISHED} is missing")
    else:
        text = published.read_text()
        if programme.BEGIN not in text or programme.END not in text:
            problems.append(f"{programme.PUBLISHED} has no measured section; a "
                            f"document that publishes figures without one has no "
                            f"place a run can be named")
        else:
            head, rest = text.split(programme.BEGIN, 1)
            body, tail = rest.split(programme.END, 1)
            rows = [line for line in body.splitlines()
                    if line.startswith("| `v7-")]
            if len(rows) < MIN_ROWS:
                problems.append(f"the measured table carries {len(rows)} row(s), "
                                f"floor is {MIN_ROWS}")
            if runs:
                want = programme.render_table(runs)
                if body.strip() != want.strip():
                    problems.append(
                        f"{programme.PUBLISHED}: the measured table is not what "
                        f"the run files say. Regenerate it with `python3 "
                        f"scripts/benchmarks/v7_benchmark.py publish` -- and if "
                        f"that changes a number, the number that stood there was "
                        f"not measured")
            for number, line in prose_measurements(head + tail):
                problems.append(
                    f"{programme.PUBLISHED}: {number!r} is published outside the "
                    f"measured table, on a line that names no run: {line.strip()!r}. "
                    f"Put it in a row with its run, or mark it {THRESHOLD}")

    known = {run["run_id"] for run in runs if "run_id" in run}
    for path in markdown_files(repo):
        for mention in sorted(set(RUN_MENTION.findall(path.read_text()))):
            if mention not in known:
                problems.append(
                    f"{path.relative_to(repo)}: cites run {mention}, and there is "
                    f"no {mention}.json in {programme.RUNS_DIR}")

    for problem in problems:
        print(f"FAIL: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"OK: {len(runs)} run(s), every published figure resolves to one.")
    return 0


def prose_measurements(text: str) -> list[tuple[str, str]]:
    """Measurements published outside the generated table.

    Fenced blocks are read like everything else. They hold the commands a reader
    runs, and those carry no figures; sample output pasted into one is exactly
    the shape this rule exists to refuse -- a result with no run behind it,
    dressed as an illustration.
    """
    found = []
    for line in text.splitlines():
        if THRESHOLD in line or RUN_MENTION.search(line):
            continue
        match = MEASUREMENT.search(line)
        if match:
            found.append((match.group(0), line))
    return found


if __name__ == "__main__":
    sys.exit(main())
