#!/usr/bin/env python3
# Copyright (c) 2026 Innovation Trigger B.V.
#
# PDFluent is available under two licences, at your option: the GNU AGPLv3, or
# the PDFluent Commercial Licence. See the LICENSE file in this repository --
# that file travels with the copy you received, which a URL does not.

"""The public API of this workspace, as data, for pdfluent.com to check against.

WHY THIS EXISTS

The website carries `data/sdk-public-api.json`, and its whole name check rests
on it. That copy states its own provenance:

    Generated by scripts/ci/export_public_api.py there.

There was no such script here. It had never reached master, so the list the site
gates on could not be reproduced by anyone -- it could only be trusted, while
the site's freshness gate counted the days since a file nobody could rebuild.
A guard reading a hand-carried input it cannot regenerate is the shape this
repository keeps finding out about too late.

WHAT IT ADDS OVER THE COPY IT REPLACES

That copy carried types and module paths. Types were never the expensive half.
`pdfluent::Sdk` was caught by a name check; `page.extract_spans()` was not,
because `extract_spans` is a *method*, and no check on this site has ever looked
at one. In the prose of the English site -- not the code blocks, which a
compiler now builds -- 554 method references name something that exists nowhere
in this workspace (#245).

So this export names methods too:

    workspace_methods   every `pub fn` in the workspace, by name
    facade_methods      the methods on PdfDocument, and whether each one works

`workspace_methods` is deliberately a set of names, not of signatures: it says
"this name exists somewhere" and nothing about the type it hangs off. That is
the right bar for prose. A name absent from 2,500 public functions is invented;
a name used on the wrong type is a shape error, and only a compiler settles that
-- `site_blocks_compile.py` does, for the code blocks.

`facade_methods` carries the runtime answer beside the name, because the
capability register already learned that lesson: `linearize()` exists, compiles,
and returns `Err(MissingDependency)` on every call. On a documentation page that
is not a method that exists.

Usage:
    export_public_api.py            # regenerate docs/PUBLIC_API.json
    export_public_api.py --check    # fail if the committed copy is stale

Exit codes:
    0  written, or up to date
    1  --check and the committed copy is stale
    2  the extraction itself is broken (a floor was breached)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
OUT = REPO / "docs" / "PUBLIC_API.json"
FACADE_SRC = REPO / "crates" / "pdfluent" / "src"

sys.path.insert(0, str(REPO / "scripts" / "ci"))
from feature_promises import PROMISES  # noqa: E402
from capability_register import binding_exports, facade_methods  # noqa: E402

# Floors. Each is a count that cannot fall without something being broken, and
# each guards a different way for this export to go quietly empty: a moved
# lib.rs, a renamed crates/ layout, a pattern that stopped matching. An export
# that returns nothing approves every name on the site.
FLOORS = {
    "modules": 20,
    "names": 60,
    "workspace_types": 400,
    "workspace_methods": 1200,
    "facade_methods": 50,
}

# `pub fn` in every shape the workspace writes it: const, async, unsafe, and
# `extern "C"` for the C ABI. One pattern rather than four, because four
# patterns are four chances to forget one.
PUB_FN = re.compile(
    r"\bpub(?:\s*\([^)]*\))?\s+"
    r"(?:const\s+|async\s+|unsafe\s+|extern\s+\"[^\"]*\"\s+)*"
    r"fn\s+(\w+)"
)
PUB_TYPE = re.compile(
    r"\bpub(?:\s*\([^)]*\))?\s+(?:struct|enum|trait|union|type)\s+(\w+)"
)
PUB_USE = re.compile(r"^[ \t]*pub use\s+([^;]+);", re.M)
PUB_MOD = re.compile(r"^[ \t]*pub mod (\w+)", re.M)


def rust_sources() -> list[Path]:
    """Every Rust source in the workspace, minus build output and vendored code.

    `target/` is excluded because build scripts generate sources into it:
    counting those would admit a name no reader can call.
    """
    out = []
    for path in (REPO / "crates").rglob("*.rs"):
        parts = set(path.parts)
        if "target" in parts or "vendor" in parts:
            continue
        out.append(path)
    return sorted(out)


def reexported(source: str) -> tuple[set[str], set[str]]:
    """(names, modules) a file's `pub use` lines make reachable, renames resolved.

    `pub use a::b::{C, D as E};` publishes `C` and `E`, not `D`. Getting that
    backwards would publish a name the crate does not have -- exactly the class
    of error this export exists to catch on the site.

    A re-exported *module* is a path whose final segment is a bare lowercase
    name (`pub use pdf_manip::text_edit;`); anything in braces is a list of
    items, whatever their case.
    """
    names: set[str] = set()
    modules: set[str] = set()
    for m in PUB_USE.finditer(source):
        clause = re.sub(r"\s+", " ", m.group(1))
        tail = clause.split("::")[-1]
        # The first character of the tail decides: `{` opens a list of items and
        # a lowercase letter starts a module. Case alone is not enough -- the
        # licence functions arrive as `pub use crate::license::{license_info,
        # ...}` and are lowercase too, and calling them modules would have the
        # site's check accept `pdfluent::license_info::` as a path.
        if tail.strip()[:1].islower():
            modules.add(re.findall(r"\w+", tail)[-1])
        tail = tail.replace("{", " ").replace("}", " ")
        for item in tail.split(","):
            words = re.findall(r"\w+", item)
            if not words:
                continue
            # `D as E` -> E; a bare `C` -> C.
            names.add(words[-1] if "as" in words else words[0])
    names.discard("as")
    return names, modules


def crate_root_surface() -> tuple[list[str], list[str]]:
    """(modules, names) a reader may write after `pdfluent::`.

    Kept apart on purpose: `pdfluent::stamp` is a wrong *path* to something
    real, `pdfluent::Sdk` is a name that never existed, and the two ask for
    different repairs (#245).

    The prelude counts. `use pdfluent::prelude::*;` is how nearly every example
    on the site opens, so a name it brings in -- `Attachment`, `Outline`,
    `DocumentStructure` -- is reachable whatever the crate root says.
    """
    lib = (FACADE_SRC / "lib.rs").read_text(errors="replace")
    prelude = (FACADE_SRC / "prelude.rs").read_text(errors="replace")

    lib_names, lib_modules = reexported(lib)
    prelude_names, _ = reexported(prelude)
    modules = {m.group(1) for m in PUB_MOD.finditer(lib)} | lib_modules
    return sorted(modules), sorted(lib_names | prelude_names)


def workspace_symbols() -> tuple[list[str], list[str]]:
    types: set[str] = set()
    methods: set[str] = set()
    for path in rust_sources():
        text = path.read_text(errors="replace")
        types.update(m.group(1) for m in PUB_TYPE.finditer(text))
        methods.update(m.group(1) for m in PUB_FN.finditer(text))
    return sorted(types), sorted(methods)


def build() -> dict:
    modules, names = crate_root_surface()
    types, methods = workspace_symbols()
    stubs = facade_methods()
    document = {
        "_": (
            "Generated by scripts/ci/export_public_api.py. Do not edit by hand. "
            "`--check` fails the build when the committed copy has drifted from "
            "the code. The website keeps a copy as data/sdk-public-api.json and "
            "gates its own build on how old that copy is (#245, #248)."
        ),
        "modules": modules,
        "names": names,
        "workspace_types": types,
        # Every `pub fn` name in the workspace. A name absent here is documented
        # by nobody's code -- see the module docstring for why this holds names
        # and not signatures.
        "workspace_methods": methods,
        # name -> works. False means the method exists, compiles, and returns an
        # error on every call: on a documentation page that is not a method.
        "facade_methods": {name: not stub for name, stub in sorted(stubs.items())},
        "binding_methods": {k: sorted(v) for k, v in sorted(binding_exports().items())},
        "promises": sorted(PROMISES),
    }
    for key, floor in FLOORS.items():
        if len(document[key]) < floor:
            print(
                f"[public-api] FLOOR: {key} holds {len(document[key])}, expected "
                f">= {floor}. The extraction is broken, not the code -- and an "
                f"empty export approves every name on the site.",
                file=sys.stderr,
            )
            sys.exit(2)
    return document


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed copy is stale")
    args = parser.parse_args()

    current = build()
    text = json.dumps(current, indent=2, ensure_ascii=False) + "\n"

    if not args.check:
        OUT.write_text(text, encoding="utf-8")
        print(
            f"[public-api] {OUT.relative_to(REPO)}: {len(current['modules'])} modules, "
            f"{len(current['names'])} root names, {len(current['workspace_types'])} types, "
            f"{len(current['workspace_methods'])} methods."
        )
        return

    if not OUT.is_file():
        print(f"[public-api] {OUT} is missing. Run without --check.", file=sys.stderr)
        sys.exit(1)
    committed = json.loads(OUT.read_text(encoding="utf-8"))
    drifted = [k for k in current if committed.get(k) != current[k]]
    if drifted:
        print(
            "[public-api] docs/PUBLIC_API.json has drifted from the code in: "
            + ", ".join(drifted)
            + "\nRun `python3 scripts/ci/export_public_api.py` and commit the result."
            + "\nA stale export approves the wrong names on pdfluent.com, which is"
            + "\nworse than having no check at all.",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"[public-api] up to date ({len(current['workspace_methods'])} public methods).")


if __name__ == "__main__":
    main()
