#!/usr/bin/env python3
# Copyright (c) 2026 Innovation Trigger B.V.
#
# PDFluent is available under two licences, at your option: the GNU AGPLv3, or
# the PDFluent Commercial Licence. See the LICENSE file in this repository --
# that file travels with the copy you received, which a URL does not.
"""The published-figure guard has to reject what it claims to reject.

Every case below is a way a number has actually got out of a building without a
measurement behind it: typed into a table by hand, left standing after the run
it came from was replaced, quoted from an axis that never ran, or written into
the prose where no table row could hold it. The tree is built from scratch each
time, the real programme and the real guard are run over it, and the repaired
tree must come back clean -- a guard that fails on everything says as little as
one that fails on nothing.

The programme is copied into the temporary tree rather than imported from the
checkout, because the guard renders the table with the programme it finds NEXT
TO the runs it is judging. That is also what makes this test bite on the
programme: change how a figure is rendered and the fabricated document stops
matching, which is the whole mechanism these cases rest on.

Nothing here touches the real tree.

Exit codes:
    0  the guard behaves
    1  it let something through, or rejected something it should not
"""

from __future__ import annotations

import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
GUARD = HERE / "a_published_number_names_its_run.py"
PROGRAMME = HERE.parent / "benchmarks" / "v7_benchmark.py"

# The day the guard is told it is. Pinned so the future-dated case stays a case
# and does not become true by waiting.
TODAY = "2026-09-06"

REGISTRY = """
[meta]
calibration_valid_days = 180

[classes.desktop-class]
description = "Persistent self-hosted runner"
runner_label = "xfa-fast"
reachable = true
calibrated = false
calibrated_on = ""
"""

RUN = {
    "run_id": "v7-2026-09-01-desktop-class-fixtures",
    "date": "2026-09-01",
    "machine_class": "desktop-class",
    "cores_observed": 8,
    "kernel": "Linux 6.8.0 x86_64",
    "commit": "0" * 40,
    "document_set": {
        "name": "fixtures",
        "directory": "/tmp/fixtures",
        "description": "Fixtures generated by this repository.",
        "licence": "ours",
        "documents": 35,
        "digest": "f" * 64,
    },
    "tools": {"verapdf": "veraPDF 1.28.2", "mutool": "mutool 1.27.2", "node": "v22.13.1"},
    "axes": {
        "performance": {
            "status": "measured",
            "documents": 35,
            "unreadable": 0,
            "measured_documents": 35,
            "open_ms": {"p50": 0.4, "p95": 3.1},
            "text_ms": {"p50": 1.2, "p95": 9.8},
            "save_ms": {"p50": 0.3, "p95": 2.0},
        },
        "archiving": {
            "status": "measured",
            "profile": "2b",
            "documents": 35,
            "conversion_failed": 0,
            "judged": 35,
            "without_verdict": 0,
            "conformant": 34,
            "conformant_pct": 97.1,
            "output_size_pct": 123.0,
            "output_size_median_pct": 118.0,
        },
        "accuracy": {
            "status": "measured",
            "documents_judged": 30,
            "too_short_to_judge": 4,
            "no_source_text": 1,
            "word_retention_median_pct": 100.0,
            "word_retention_p5_pct": 98.6,
            "below_95pct_retention": 0,
            "char_retention_median_pct": 100.0,
            "separator_broken": 0,
            "visibly_changed": 2,
            "render_dpi": 50,
            "render_pages_per_document": 3,
        },
    },
    "axes_skipped": [],
}

DOCUMENT = """# The benchmark programme

Three axes, measured together.

## Measured

{begin}
{end}

## What these figures do not say

The fixtures set is ours and small.
"""


def build(root: pathlib.Path) -> None:
    """The repaired tree: a programme, a registry, one run, a published table."""
    (root / "benchmarks" / "runs" / "v7").mkdir(parents=True)
    (root / "scripts" / "benchmarks").mkdir(parents=True)
    shutil.copy(PROGRAMME, root / "scripts" / "benchmarks" / "v7_benchmark.py")

    (root / "benchmarks" / "BASELINE_HARDWARE.toml").write_text(REGISTRY)
    write_run(root, RUN)

    programme = load_programme(root)
    (root / "benchmarks" / "V7_BENCHMARK_PROGRAMME.md").write_text(
        DOCUMENT.format(begin=programme.BEGIN, end=programme.END))
    publish(root)


def load_programme(root: pathlib.Path):
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        f"v7_under_test_{root.name}", root / "scripts" / "benchmarks" / "v7_benchmark.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_run(root: pathlib.Path, run: dict) -> None:
    path = root / "benchmarks" / "runs" / "v7" / f"{run['run_id']}.json"
    path.write_text(json.dumps(run, indent=2, sort_keys=True) + "\n")


def read_run(root: pathlib.Path, run_id: str) -> dict:
    path = root / "benchmarks" / "runs" / "v7" / f"{run_id}.json"
    return json.loads(path.read_text())


def publish(root: pathlib.Path) -> None:
    proc = subprocess.run(
        [sys.executable, str(root / "scripts" / "benchmarks" / "v7_benchmark.py"),
         "--repo", str(root), "publish"],
        capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"the programme could not publish the fabricated tree: "
                         f"{proc.stdout}{proc.stderr}")


def document(root: pathlib.Path) -> pathlib.Path:
    return root / "benchmarks" / "V7_BENCHMARK_PROGRAMME.md"


def run_guard(root: pathlib.Path) -> tuple[int, str]:
    proc = subprocess.run(
        [sys.executable, str(GUARD), "--repo", str(root), "--today", TODAY],
        capture_output=True, text=True)
    return proc.returncode, proc.stdout + proc.stderr


# ---- the cases, each one a way a number got out without a measurement --------
def a_figure_edited_by_hand(root: pathlib.Path) -> None:
    """The oldest one. The table says 97.1%; somebody prefers 99.1%."""
    path = document(root)
    path.write_text(path.read_text().replace("97.1", "99.1"))


def the_run_is_deleted_from_under_it(root: pathlib.Path) -> None:
    (root / "benchmarks" / "runs" / "v7" /
     f"{RUN['run_id']}.json").unlink()


def a_figure_in_the_prose(root: pathlib.Path) -> None:
    """A number where no row can hold it, which is where claims wander to."""
    path = document(root)
    path.write_text(path.read_text().replace(
        "The fixtures set is ours and small.",
        "The fixtures set is ours and small, and 98.0% of it converts."))


def a_threshold_in_the_prose(root: pathlib.Path) -> None:
    """The good direction: a threshold, marked. This one must stay clean."""
    path = document(root)
    path.write_text(path.read_text().replace(
        "The fixtures set is ours and small.",
        "Retention below 95% is counted apart. (threshold)"))


def a_figure_hidden_in_a_fenced_block(root: pathlib.Path) -> None:
    """Sample output is the oldest way to publish a number without a run."""
    path = document(root)
    path.write_text(path.read_text() + "\n```\nconformant 34 of 35 documents\n```\n")


def a_number_from_an_axis_that_never_ran(root: pathlib.Path) -> None:
    run = read_run(root, RUN["run_id"])
    run["axes"]["archiving"] = {
        "status": "skipped",
        "why": "verapdf is not on PATH",
        "conformant_pct": 97.1,
    }
    write_run(root, run)


def a_skipped_axis_without_a_reason(root: pathlib.Path) -> None:
    run = read_run(root, RUN["run_id"])
    run["axes"]["accuracy"] = {"status": "skipped", "why": ""}
    write_run(root, run)
    publish(root)


def a_run_on_a_machine_nobody_described(root: pathlib.Path) -> None:
    run = read_run(root, RUN["run_id"])
    run["machine_class"] = "some-laptop"
    write_run(root, run)
    publish(root)


def a_run_whose_file_and_identifier_disagree(root: pathlib.Path) -> None:
    path = root / "benchmarks" / "runs" / "v7" / f"{RUN['run_id']}.json"
    path.rename(path.with_name("v7-2026-09-02-desktop-class-fixtures.json"))


def a_run_dated_in_the_future(root: pathlib.Path) -> None:
    run = read_run(root, RUN["run_id"])
    run["date"] = "2099-01-01"
    write_run(root, run)


def a_run_that_names_no_commit(root: pathlib.Path) -> None:
    run = read_run(root, RUN["run_id"])
    run["commit"] = ""
    write_run(root, run)


def an_axis_that_is_simply_absent(root: pathlib.Path) -> None:
    run = read_run(root, RUN["run_id"])
    del run["axes"]["accuracy"]
    write_run(root, run)


def a_citation_to_a_run_that_does_not_exist(root: pathlib.Path) -> None:
    (root / "benchmarks" / "NOTES.md").write_text(
        "Measured in v7-2026-08-30-desktop-class-fixtures.\n")


def nothing_to_check_at_all(root: pathlib.Path) -> None:
    """The floor. An empty run directory reports the same green as a good tree."""
    for path in (root / "benchmarks" / "runs" / "v7").glob("*.json"):
        path.unlink()
    path = document(root)
    programme = load_programme(root)
    head, rest = path.read_text().split(programme.BEGIN, 1)
    _, tail = rest.split(programme.END, 1)
    path.write_text(f"{head}{programme.BEGIN}\n{programme.END}{tail}")


CASES = [
    ("a figure in the table was edited by hand", a_figure_edited_by_hand,
     "not what the run files say"),
    ("the run is deleted from under a published figure",
     the_run_is_deleted_from_under_it, None),
    ("a figure stands in the prose, naming no run", a_figure_in_the_prose,
     "outside the measured table"),
    ("a figure is hidden in a fenced block", a_figure_hidden_in_a_fenced_block,
     "outside the measured table"),
    ("an axis that measured nothing still reports a figure",
     a_number_from_an_axis_that_never_ran, "measured nothing and still reports"),
    ("an axis was skipped without saying why", a_skipped_axis_without_a_reason,
     "without saying why"),
    ("a run names a machine class nobody described",
     a_run_on_a_machine_nobody_described, "BASELINE_HARDWARE"),
    ("a run's file and identifier disagree",
     a_run_whose_file_and_identifier_disagree, "cannot be cited"),
    ("a run is dated in the future", a_run_dated_in_the_future, "in the future"),
    ("a run names no commit", a_run_that_names_no_commit, "names no commit"),
    ("one of the three axes is simply absent", an_axis_that_is_simply_absent,
     "All three are reported together"),
    ("a document cites a run that does not exist",
     a_citation_to_a_run_that_does_not_exist, "there is no"),
    ("there is nothing left to check", nothing_to_check_at_all, "floor"),
]

# Mutations that must NOT be rejected. A guard that goes red on a marked
# threshold teaches people to write numbers somewhere it cannot see them.
CLEAN_CASES = [
    ("a threshold in the prose, marked as one", a_threshold_in_the_prose),
]


def main() -> int:
    failures: list[str] = []

    for description, mutate, reason in CASES:
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            build(root)
            mutate(root)
            code, output = run_guard(root)
            caught = code != 0 and (reason is None or reason in output)
            print(f"  {'caught' if caught else 'MISSED':7} exit={code}  {description}")
            if not caught:
                failures.append(description)
                for line in output.strip().splitlines():
                    print(f"          {line}")

    for description, mutate in CLEAN_CASES:
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            build(root)
            mutate(root)
            code, output = run_guard(root)
            print(f"  {'clean' if code == 0 else 'FALSE+':7} exit={code}  {description}")
            if code != 0:
                failures.append(description)
                for line in output.strip().splitlines():
                    print(f"          {line}")

    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp)
        build(root)
        code, output = run_guard(root)
        print(f"  {'clean' if code == 0 else 'FALSE+':7} exit={code}  the repaired tree")
        if code != 0:
            failures.append("the repaired tree is rejected")
            for line in output.strip().splitlines():
                print(f"          {line}")

    if failures:
        print(f"\nFAIL: {len(failures)} case(s): {'; '.join(failures)}")
        return 1
    print(f"\nOK: {len(CASES)} rejections, {len(CLEAN_CASES) + 1} clean trees.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
