[package]
name = "xfa-dom-resolver"
version.workspace = true
edition.workspace = true
license-file = "LICENSE"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "XFA template and data DOM with SOM-path resolution."

[dependencies]
roxmltree.workspace = true
thiserror.workspace = true
