/**
 * XFA-WASM TypeScript bindings.
 *
 * Provides typed wrappers around the WASM-exported classes.
 */

// Re-export WASM init and raw classes
// @ts-ignore — generated by wasm-bindgen
export { default as init, XfaEngine as RawXfaEngine, PdfDoc as RawPdfDoc } from '../pkg/xfa_wasm';

// --- Type definitions ---

export interface FieldDef {
  name: string;
  value?: string;
  calculate?: string;
  validate?: string;
}

export interface PdfMetadata {
  title: string | null;
  author: string | null;
  subject: string | null;
  keywords: string | null;
  creator: string | null;
  producer: string | null;
}

export interface SignatureInfo {
  field_name: string;
  signer: string | null;
  reason: string | null;
  location: string | null;
  signing_time: string | null;
  sub_filter: string | null;
}

export interface ComplianceIssue {
  rule: string;
  severity: string;
  message: string;
}

export interface ComplianceReport {
  compliant: boolean;
  errors: number;
  warnings: number;
  issues: ComplianceIssue[];
}

export interface DssInfo {
  has_ltv: boolean;
  certificates: number;
  ocsp_responses: number;
  crls: number;
  vri_entries: number;
}

// --- XFA Forms wrapper ---

// @ts-ignore
import { XfaEngine as RawEngine } from '../pkg/xfa_wasm';

export class XfaForms {
  private engine: InstanceType<typeof RawEngine>;

  private constructor(engine: InstanceType<typeof RawEngine>) {
    this.engine = engine;
  }

  static fromFields(fields: FieldDef[]): XfaForms {
    const raw = RawEngine.fromFields(JSON.stringify(fields));
    return new XfaForms(raw);
  }

  static fromJson(json: string): XfaForms {
    const raw = RawEngine.fromJson(json);
    return new XfaForms(raw);
  }

  runCalculations(): void {
    this.engine.runCalculations();
  }

  exportJson(): Record<string, unknown> {
    return JSON.parse(this.engine.exportJson());
  }

  exportSchema(): Record<string, unknown> {
    return JSON.parse(this.engine.exportSchema());
  }

  importJson(data: Record<string, unknown> | string): void {
    const json = typeof data === 'string' ? data : JSON.stringify(data);
    this.engine.importJson(json);
  }

  getFieldValue(path: string): string | undefined {
    return this.engine.getFieldValue(path) ?? undefined;
  }

  setFieldValue(path: string, value: string): boolean {
    return this.engine.setFieldValue(path, value);
  }

  get nodeCount(): number {
    return this.engine.nodeCount();
  }

  static version(): string {
    return RawEngine.version();
  }
}

// --- PDF Document wrapper ---

// @ts-ignore
import { PdfDoc as RawPdf } from '../pkg/xfa_wasm';

export class PdfDocument {
  private doc: InstanceType<typeof RawPdf>;

  private constructor(doc: InstanceType<typeof RawPdf>) {
    this.doc = doc;
  }

  static open(data: Uint8Array): PdfDocument {
    const raw = RawPdf.open(data);
    return new PdfDocument(raw);
  }

  get pageCount(): number {
    return this.doc.pageCount();
  }

  get metadata(): PdfMetadata {
    return JSON.parse(this.doc.metadata());
  }

  get signatures(): SignatureInfo[] {
    return JSON.parse(this.doc.signatures());
  }

  get hasSignatures(): boolean {
    return this.doc.hasSignatures();
  }

  validatePdfA(level: string = 'pdf-a2b'): ComplianceReport {
    return JSON.parse(this.doc.validatePdfA(level));
  }

  get dssInfo(): DssInfo | null {
    const json = this.doc.dssInfo();
    return json ? JSON.parse(json) : null;
  }
}
