// Copyright (c) 2026 Innovation Trigger B.V. All rights reserved.
//
// This software is proprietary. The PDFluent application is free to use,
// including for commercial purposes. Redistribution, or extraction or reuse
// of its components (including the embedded PDF engine), requires a licence.
// See https://pdfluent.com/license for terms.

package com.pdfluent;

import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The JNI document surface of {@code libpdfluent_java}, called on a real
 * document.
 *
 * <p>This replaces {@code com.xfa.pdf.PdfDocumentTest}. That suite went through
 * the legacy {@code com.xfa.pdf} wrappers, whose natives resolve to
 * {@code Java_com_xfa_pdf_PdfDocument_*} -- symbols the library has not
 * exported since 18742a72 renamed them to {@code Java_com_pdfluent_*}. Every
 * one of its tests errored with {@code UnsatisfiedLinkError}, and because no
 * CI job ran {@code mvn test} for this crate, nobody saw it
 * (pdfluent/pdfluent-internal#310).
 *
 * <p>The fixture is generated by {@code pdf-manip}'s {@code java_binding_fixture}
 * example and committed; {@code scripts/ci/the_java_fixture_is_the_one_we_generate.py}
 * keeps the two in step. It carries one page with the text
 * "PDFluent Java binding fixture" and a Producer of "PDFluent", which is what
 * the assertions below read back.
 *
 * <p>Run (from the repository root):
 * <pre>
 *   cargo build -p pdf-java
 *   mvn -f crates/pdf-java/pom.xml -Dnative.lib.dir="$PWD/target/debug" test
 * </pre>
 */
class PdfluentDocumentJniTest {

    private static byte[] fixtureBytes() throws Exception {
        try (InputStream in = PdfluentDocumentJniTest.class.getResourceAsStream("/binding-fixture.pdf")) {
            assertNotNull(in, "binding-fixture.pdf not found on the test classpath");
            return in.readAllBytes();
        }
    }

    @Test
    void opensAndCountsPages() throws Exception {
        long h = PdfluentDocument.nativeOpen(fixtureBytes());
        assertNotEquals(0L, h, "nativeOpen returned a zero handle without throwing");
        try {
            assertEquals(1, PdfluentDocument.nativePageCount(h),
                    "the generated fixture has exactly one page");
        } finally {
            PdfluentDocument.nativeClose(h);
        }
    }

    @Test
    void extractsTheTextTheGeneratorWrote() throws Exception {
        long h = PdfluentDocument.nativeOpen(fixtureBytes());
        try {
            String text = PdfluentDocument.nativeExtractText(h, 0);
            assertNotNull(text);
            assertTrue(text.contains("PDFluent Java binding fixture"),
                    "page 0 text does not contain the fixture heading; got: " + text);
        } finally {
            PdfluentDocument.nativeClose(h);
        }
    }

    @Test
    void readsMetadataAndReturnsNullForAbsentKeys() throws Exception {
        long h = PdfluentDocument.nativeOpen(fixtureBytes());
        try {
            assertEquals("PDFluent", PdfluentDocument.nativeGetMetadata(h, "Producer"));
            assertEquals("PDFluent Java binding fixture",
                    PdfluentDocument.nativeGetMetadata(h, "Title"));
            assertNull(PdfluentDocument.nativeGetMetadata(h, "Keywords"),
                    "the generator sets no Keywords, so the binding must return null");
        } finally {
            PdfluentDocument.nativeClose(h);
        }
    }

    @Test
    void validatesPdfaAndReturnsTheFlatReport() throws Exception {
        Path tmp = Files.createTempFile("pdfluent-jni-", ".pdf");
        try {
            Files.write(tmp, fixtureBytes());
            String[] report = PdfUtils.nativeValidatePdfa(tmp.toString(), "2b");
            assertNotNull(report, "nativeValidatePdfa returned null without throwing");
            assertTrue(report.length >= 3, "report shorter than its three-field header");
            assertTrue(report[0].equals("true") || report[0].equals("false"),
                    "compliant flag is not a boolean: " + report[0]);
            assertTrue(Integer.parseInt(report[1]) >= 0, "error count");
            assertTrue(Integer.parseInt(report[2]) >= 0, "warning count");
            assertEquals(0, (report.length - 3) % 3,
                    "issues must arrive as (rule, severity, message) triples");
        } finally {
            Files.deleteIfExists(tmp);
        }
    }

    @Test
    void garbageBytesThrowParseExceptionNotACrash() {
        byte[] garbage = {0x00, 0x01, 0x02, 0x03, 0x04};
        assertThrows(PdfluentParseException.class,
                () -> PdfluentDocument.nativeOpen(garbage));
    }

    @Test
    void aClosedHandleIsRefusedNotDereferenced() {
        // Handle 0 is what a closed document holds. The binding must throw,
        // not read through it.
        assertEquals(0, PdfluentDocument.nativePageCount(0L));
        PdfluentException e = assertThrows(PdfluentException.class,
                () -> PdfluentDocument.nativeExtractText(0L, 0));
        assertTrue(e.getMessage().contains("closed"), e.getMessage());
    }
}
