package com.pdfluent;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Signed-licence lifecycle tests exercising the JNI path in libpdfluent_java
 * (pdf-java/src/lib.rs).
 *
 * <p>The test fixtures are shared with the other SDK bindings — same public key,
 * same payloads — to prove cross-language parity.
 *
 * <p>The OnceLock in the Rust core is process-global, so tests are ordered to
 * run in a single well-defined sequence:
 * <ol>
 *   <li>Error paths before public key is set.</li>
 *   <li>Public-key validation errors.</li>
 *   <li>setPublicKey succeeds and is idempotent.</li>
 *   <li>Payload error paths (expired, wrong key, malformed).</li>
 *   <li>Happy path — valid payload activates developer tier.</li>
 *   <li>Idempotency — re-activating same tier is a no-op.</li>
 * </ol>
 *
 * <p>Run:
 * <pre>
 *   cargo build --manifest-path crates/pdf-java/Cargo.toml --release
 *   cd crates/pdf-java
 *   mvn test -Djava.library.path=../../target/release \
 *            -Dtest=PdfluentLicensingSignedPayloadJniTest
 * </pre>
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PdfluentLicensingSignedPayloadJniTest {

    // -------------------------------------------------------------------------
    // Cross-language test fixtures (generated by /tmp/fixture_gen, verified
    // against the Rust xfa-license verifier).
    // -------------------------------------------------------------------------

    private static final String PUBLIC_KEY_HEX =
            "175cd1a23d436d170e74046becf56364b547778f15a350f29bfb776de3a41e05";

    /** Basic-tier, expires year 3000, valid signature. */
    private static final String VALID_PAYLOAD =
            "{\n" +
            "  \"licensee\": \"Test Corp\",\n" +
            "  \"email\": \"ci@pdfluent.test\",\n" +
            "  \"company\": \"PDFluent CI\",\n" +
            "  \"tier\": \"basic\",\n" +
            "  \"seats\": 5,\n" +
            "  \"issued_at\": 1700000000,\n" +
            "  \"expires_at\": 32503680000,\n" +
            "  \"features\": [\n" +
            "    \"xfa\"\n" +
            "  ],\n" +
            "  \"signature\": \"uSoL4HwHIMBAIhKrvdbLlBiTOczw78z71If/rjfBaiihqSu+jbZasnuWA3pfuJqh9ofKH2ACvZha9J3Ga6YMCw==\"\n" +
            "}";

    /** Same key, same fields, but expires 2020-01-01 (in the past). */
    private static final String EXPIRED_PAYLOAD =
            "{\n" +
            "  \"licensee\": \"Test Corp\",\n" +
            "  \"email\": \"ci@pdfluent.test\",\n" +
            "  \"company\": \"PDFluent CI\",\n" +
            "  \"tier\": \"basic\",\n" +
            "  \"seats\": 5,\n" +
            "  \"issued_at\": 1700000000,\n" +
            "  \"expires_at\": 1577836800,\n" +
            "  \"features\": [\n" +
            "    \"xfa\"\n" +
            "  ],\n" +
            "  \"signature\": \"3xvLjs5CjNf8pOKCPgMGJe+8bsTlc8LNSDYjPzqI1KjmvkSRlwbyL4/frEqlcDpcPfa8+STiMnaXpTM8m6h8Bw==\"\n" +
            "}";

    /** Signed with a DIFFERENT key — signature will not verify. */
    private static final String WRONG_KEY_PAYLOAD =
            "{\n" +
            "  \"licensee\": \"Test Corp\",\n" +
            "  \"email\": \"ci@pdfluent.test\",\n" +
            "  \"company\": \"PDFluent CI\",\n" +
            "  \"tier\": \"basic\",\n" +
            "  \"seats\": 5,\n" +
            "  \"issued_at\": 1700000000,\n" +
            "  \"expires_at\": 32503680000,\n" +
            "  \"features\": [\n" +
            "    \"xfa\"\n" +
            "  ],\n" +
            "  \"signature\": \"Xr0pO67Klst4i0r5dzXceCXSJP1B+EWtCBtDT5gDyOdyjhgeev7uEo+x0QPtZko1KGTajHwZj6TZjjm6N4EuAQ==\"\n" +
            "}";

    private static byte[] publicKeyBytes() {
        String hex = PUBLIC_KEY_HEX;
        byte[] result = new byte[hex.length() / 2];
        for (int i = 0; i < result.length; i++) {
            result[i] = (byte) Integer.parseInt(hex.substring(2 * i, 2 * i + 2), 16);
        }
        return result;
    }

    // -------------------------------------------------------------------------
    // Order 1 — Error paths before public key is set
    // -------------------------------------------------------------------------

    @Test @Order(1)
    void activatePayloadBeforePublicKeyThrows() {
        PdfluentLicenseException ex = assertThrows(
                PdfluentLicenseException.class,
                () -> PdfluentLicensing.activatePayload(VALID_PAYLOAD),
                "activatePayload must fail before public key is configured"
        );
        assertEquals("E-LICENSE-INVALID", ex.getCode(),
                "wrong code before public key");
    }

    // -------------------------------------------------------------------------
    // Order 2 — setPublicKey validation errors
    // -------------------------------------------------------------------------

    @Test @Order(2)
    void setPublicKeyNullThrows() {
        assertThrows(NullPointerException.class,
                () -> PdfluentLicensing.setPublicKey(null));
    }

    @Test @Order(3)
    void setPublicKeyWrongLengthThrows() {
        PdfluentLicenseException ex = assertThrows(
                PdfluentLicenseException.class,
                () -> PdfluentLicensing.setPublicKey(new byte[]{0x01, 0x02}),
                "16-byte key must be rejected"
        );
        assertEquals("E-LICENSE-INVALID", ex.getCode());
    }

    // -------------------------------------------------------------------------
    // Order 4 — setPublicKey succeeds and is idempotent
    // -------------------------------------------------------------------------

    @Test @Order(4)
    void setPublicKeyValidSucceeds() {
        assertDoesNotThrow(() -> PdfluentLicensing.setPublicKey(publicKeyBytes()));
    }

    @Test @Order(5)
    void setPublicKeyIdempotentWithSameKey() {
        assertDoesNotThrow(() -> PdfluentLicensing.setPublicKey(publicKeyBytes()),
                "second call with same key must not throw");
    }

    // -------------------------------------------------------------------------
    // Order 6 — Payload error paths (after key is configured)
    // -------------------------------------------------------------------------

    @Test @Order(6)
    void activatePayloadNullThrows() {
        assertThrows(NullPointerException.class,
                () -> PdfluentLicensing.activatePayload(null));
    }

    @Test @Order(7)
    void activatePayloadMalformedJsonThrowsInvalid() {
        PdfluentLicenseException ex = assertThrows(
                PdfluentLicenseException.class,
                () -> PdfluentLicensing.activatePayload("{not json")
        );
        assertEquals("E-LICENSE-INVALID", ex.getCode());
    }

    @Test @Order(8)
    void activatePayloadExpiredThrowsExpiredCode() {
        PdfluentLicenseException ex = assertThrows(
                PdfluentLicenseException.class,
                () -> PdfluentLicensing.activatePayload(EXPIRED_PAYLOAD)
        );
        assertEquals("E-LICENSE-EXPIRED", ex.getCode(),
                "expired payload must carry E-LICENSE-EXPIRED, got: " + ex.getCode());
    }

    @Test @Order(9)
    void activatePayloadWrongSignatureThrowsInvalidSignatureCode() {
        PdfluentLicenseException ex = assertThrows(
                PdfluentLicenseException.class,
                () -> PdfluentLicensing.activatePayload(WRONG_KEY_PAYLOAD)
        );
        assertEquals("E-LICENSE-INVALID-SIGNATURE", ex.getCode(),
                "wrong-key payload must carry E-LICENSE-INVALID-SIGNATURE, got: " + ex.getCode());
    }

    // -------------------------------------------------------------------------
    // Order 10 — Happy path
    // -------------------------------------------------------------------------

    @Test @Order(10)
    void activatePayloadValidSucceeds() {
        // xfa-license Basic tier → pdfluent Developer (tier int = 1)
        assertDoesNotThrow(() -> PdfluentLicensing.activatePayload(VALID_PAYLOAD));
        assertEquals(1, PdfluentLicensing.effectiveTier(),
                "Basic → Developer mapping: expected tier 1");
    }

    // -------------------------------------------------------------------------
    // Order 11 — Idempotency after activation
    // -------------------------------------------------------------------------

    @Test @Order(11)
    void activatePayloadIdempotentAfterActivation() {
        // Re-activating the same tier must be a no-op (OnceLock idempotency).
        assertDoesNotThrow(() -> PdfluentLicensing.activatePayload(VALID_PAYLOAD));
        assertEquals(1, PdfluentLicensing.effectiveTier());
    }

    // -------------------------------------------------------------------------
    // Order 12 — Auto-detect via nativeActivateKey
    // -------------------------------------------------------------------------

    @Test @Order(12)
    void activateKeyAutoDetectsSignedJsonPayload() {
        // nativeActivateKey routes to set_license_payload when the key starts with '{'.
        assertDoesNotThrow(() -> PdfluentLicensing.activateKey(VALID_PAYLOAD));
        assertEquals(1, PdfluentLicensing.effectiveTier());
    }
}
