/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Information about a single annotation. */
export interface AnnotationInfo {
  /** Annotation subtype (e.g., "Text", "Link", "Widget"). */
  annotationType: string
  /** Annotation rectangle [x0, y0, x1, y1] in page coordinates. */
  rect?: Array<number>
  /** Text contents of the annotation, if any. */
  contents?: string
  /** Author (T entry), if any. */
  author?: string
  /** Whether the annotation is hidden. */
  hidden: boolean
  /** Whether the annotation should print. */
  printable: boolean
}
/** Document metadata. */
export interface DocumentInfo {
  title?: string
  author?: string
  subject?: string
  keywords?: string
  creator?: string
  producer?: string
}
/** A bookmark / outline item. */
export interface BookmarkItem {
  title: string
  page?: number
  children: Array<BookmarkItem>
}
/** Render options passed from JavaScript. */
export interface RenderOpts {
  /** DPI (default: 72.0). */
  dpi?: number
  /** Background RGBA [r, g, b, a] each 0.0–1.0. */
  background?: Array<number>
  /** Force output width in pixels. */
  width?: number
  /** Force output height in pixels. */
  height?: number
}
/** Rendered page result returned to JavaScript. */
export interface RenderResult {
  /** RGBA pixel data. */
  data: Buffer
  /** Width in pixels. */
  width: number
  /** Height in pixels. */
  height: number
}
/** Page geometry information. */
export interface PageGeometry {
  /** Width in PDF points. */
  width: number
  /** Height in PDF points. */
  height: number
  /** Rotation in degrees. */
  rotation: number
}
/** A text span at a specific position. */
export interface TextSpanInfo {
  /** The extracted text. */
  text: string
  /** X position in user space. */
  x: number
  /** Y position in user space. */
  y: number
  /** Approximate font size. */
  fontSize: number
}
/** A block of text (grouped by vertical proximity). */
export interface TextBlockInfo {
  /** Concatenated text of the block. */
  text: string
  /** Individual spans within this block. */
  spans: Array<TextSpanInfo>
}
/** Result of a text redaction operation. */
export interface RedactionResult {
  /** Number of text matches found. */
  matchesFound: number
  /** Number of page areas redacted. */
  areasRedacted: number
  /** Number of pages affected. */
  pagesAffected: number
}
/** Signature validation result. */
export interface SignatureResult {
  /** Validation status: "valid", "invalid", or "unknown". */
  status: string
  /** Reason for invalid/unknown status. */
  reason?: string
  /** Fully qualified field name. */
  fieldName: string
  /** Signer common name, if available. */
  signer?: string
  /** Signing timestamp, if available. */
  timestamp?: string
}
/** PDF/A compliance issue. */
export interface ComplianceIssueInfo {
  /** Rule identifier. */
  rule: string
  /** Severity: "error", "warning", or "info". */
  severity: string
  /** Human-readable description. */
  message: string
}
/** PDF/A compliance report. */
export interface ComplianceReportInfo {
  /** Whether the document is compliant. */
  compliant: boolean
  /** Number of errors. */
  errorCount: number
  /** Number of warnings. */
  warningCount: number
  /** All issues found. */
  issues: Array<ComplianceIssueInfo>
}
/** Information about a single form field. */
export interface FormFieldInfo {
  /** Fully qualified field name (e.g., "form.name"). */
  name: string
  /** Field type: "text", "button", "choice", or "signature". */
  fieldType: string
  /** Current value, if any. */
  value?: string
  /** Whether the field is read-only. */
  readOnly: boolean
}
/**
 * Open a PDF from a file path.
 *
 * Convenience wrapper around `PdfDocument.open` for path-based workflows.
 */
export declare function openPdf(path: string): PdfDocument
/**
 * Merge multiple PDF files into a single output file.
 *
 * Reads each input path, concatenates all pages in order, and writes the
 * result to `output_path`. All input files must be valid, readable PDFs.
 *
 * ```js
 * const { mergePdfs } = require('@xfa-engine/pdf-node');
 * await mergePdfs(['a.pdf', 'b.pdf'], 'merged.pdf');
 * ```
 */
export declare function mergePdfs(paths: Array<string>, outputPath: string): void
/**
 * Validate a PDF file against a PDF/A conformance level.
 *
 * `level` must be one of: "1a", "1b", "2a", "2b", "2u", "3a", "3b", "3u".
 *
 * Returns a `ComplianceReportInfo` with `compliant`, `errorCount`,
 * `warningCount`, and a list of `issues`.
 *
 * ```js
 * const { validatePdfA } = require('@xfa-engine/pdf-node');
 * const report = validatePdfA('document.pdf', '2b');
 * console.log(report.compliant, report.errorCount);
 * ```
 */
export declare function validatePdfa(path: string, level: string): ComplianceReportInfo
/**
 * A PDF document handle.
 *
 * Open a document with `PdfDocument.open(buffer)` or
 * `PdfDocument.openAsync(buffer)`.
 */
export declare class PdfDocument {
  /** Open a PDF from a Buffer (synchronous). */
  static open(data: Buffer): PdfDocument
  /** Open a PDF from a Buffer (async — runs on worker thread). */
  static openAsync(data: Buffer): Promise<PdfDocument>
  /** Open a password-protected PDF. */
  static openWithPassword(data: Buffer, password: string): PdfDocument
  /** Number of pages in the document. */
  get pageCount(): number
  /** Get document metadata. */
  info(): DocumentInfo
  /** Get a page handle (0-based index). */
  page(index: number): PdfPage
  /** Render a single page to RGBA pixels (synchronous). */
  renderPage(index: number, options?: RenderOpts | undefined | null): RenderResult
  /** Render a single page to RGBA pixels (async — worker thread). */
  renderPageAsync(index: number, options?: RenderOpts | undefined | null): Promise<RenderResult>
  /** Generate a thumbnail for a page (async). */
  thumbnail(index: number, maxDimension?: number | undefined | null): Promise<RenderResult>
  /** Extract text from a page (synchronous). */
  extractText(index: number): string
  /** Extract text from a page (async — worker thread). */
  extractTextAsync(index: number): Promise<string>
  /** Search for text across all pages. Returns 0-based page indices. */
  searchText(query: string): Array<number>
  /** Get document bookmarks / outline. */
  bookmarks(): Array<BookmarkItem>
  /** Get page geometry (dimensions, rotation). */
  pageGeometry(index: number): PageGeometry
  /** Render all pages in parallel (async). */
  renderAll(options?: RenderOpts | undefined | null): Promise<Array<RenderResult>>
  /** Extract structured text blocks from a page. */
  extractTextBlocks(index: number): Array<TextBlockInfo>
  /** Get all form fields in the document. */
  formFields(): Array<FormFieldInfo>
  /** Get the value of a form field by its fully qualified name. */
  getFieldValue(name: string): string | null
  /**
   * Set the value of a form field by its fully qualified name.
   *
   * The change is persisted to the document — a subsequent `save()` will
   * write the updated value.
   */
  setFieldValue(name: string, value: string): void
  /** Get annotations on a specific page (0-based index). */
  annotations(pageIndex: number): Array<AnnotationInfo>
  /** Validate all digital signatures in the document. */
  validateSignatures(): Array<SignatureResult>
  /**
   * Save the document to a file path.
   *
   * Writes the current (possibly modified) document to disk. Any changes
   * from `setFieldValue`, `addAnnotation`, or `redactText` are included.
   */
  save(path: string): void
  /**
   * Add an annotation to a page (0-based index).
   *
   * `annot_type` must be one of: `"highlight"`, `"freetext"`, `"note"`,
   * `"underline"`, `"strikeout"`, `"squiggly"`.
   *
   * `rect` is `[x0, y0, x1, y1]` in PDF user-space coordinates.
   * For `"freetext"`, `content` becomes the visible text.
   */
  addAnnotation(page: number, annotType: string, rect: Array<number>, content?: string | undefined | null): void
  /**
   * Redact all occurrences of `search_term` on a page (0-based index).
   *
   * Pass `page = u32::MAX` (or omit via a wrapper) to redact across all pages.
   * The document is modified in-place; call `save()` to persist.
   *
   * Returns a summary of what was redacted.
   */
  redactText(searchTerm: string, page?: number | undefined | null): RedactionResult
  /**
   * Encrypt the document and write it to `output_path`.
   *
   * Uses AES-256 with `password` as both the user and owner password.
   * The in-memory document is not modified — encryption is applied to a
   * temporary clone and only the written file is encrypted.
   */
  encrypt(outputPath: string, password: string): void
  /**
   * Remove encryption and write the decrypted document to `output_path`.
   *
   * Only useful if the document was opened with `openWithPassword`.
   * After this call the saved file has no password protection.
   */
  decrypt(outputPath: string): void
  /**
   * Validate the document against a PDF/A conformance level.
   *
   * Level is specified as a string: "1a", "1b", "2a", "2b", "2u", "3a", "3b", "3u".
   */
  validatePdfa(level: string): ComplianceReportInfo
}
/** A handle to a single page within a PDF document. */
export declare class PdfPage {
  /** Page index (0-based). */
  get index(): number
  /** Page width in PDF points. */
  get width(): number
  /** Page height in PDF points. */
  get height(): number
  /** Page geometry (dimensions + rotation). */
  geometry(): PageGeometry
  /** Render this page to RGBA pixels (synchronous). */
  render(options?: RenderOpts | undefined | null): RenderResult
  /** Render this page to RGBA pixels (async — worker thread). */
  renderAsync(options?: RenderOpts | undefined | null): Promise<RenderResult>
  /** Generate a thumbnail (async). */
  thumbnail(maxDimension?: number | undefined | null): Promise<RenderResult>
  /** Extract text from this page. */
  text(): string
  /** Extract text from this page (async). */
  textAsync(): Promise<string>
  /** Extract structured text blocks from this page. */
  textBlocks(): Array<TextBlockInfo>
  /** Get annotations on this page. */
  annotations(): Array<AnnotationInfo>
}
