/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Information about a single annotation. */
export interface AnnotationInfo {
  /** Annotation subtype (e.g., "Text", "Link", "Widget"). */
  annotationType: string
  /** Annotation rectangle [x0, y0, x1, y1] in page coordinates. */
  rect?: Array<number>
  /** Text contents of the annotation, if any. */
  contents?: string
  /** Author (T entry), if any. */
  author?: string
  /** Whether the annotation is hidden. */
  hidden: boolean
  /** Whether the annotation should print. */
  printable: boolean
}
/** Document metadata. */
export interface DocumentInfo {
  title?: string
  author?: string
  subject?: string
  keywords?: string
  creator?: string
  producer?: string
}
/** A bookmark / outline item. */
export interface BookmarkItem {
  title: string
  page?: number
  children: Array<BookmarkItem>
}
/** Render options passed from JavaScript. */
export interface RenderOpts {
  /** DPI (default: 72.0). */
  dpi?: number
  /** Background RGBA [r, g, b, a] each 0.0–1.0. */
  background?: Array<number>
  /** Force output width in pixels. */
  width?: number
  /** Force output height in pixels. */
  height?: number
}
/** Rendered page result returned to JavaScript. */
export interface RenderResult {
  /** RGBA pixel data. */
  data: Buffer
  /** Width in pixels. */
  width: number
  /** Height in pixels. */
  height: number
}
/** Page geometry information. */
export interface PageGeometry {
  /** Width in PDF points. */
  width: number
  /** Height in PDF points. */
  height: number
  /** Rotation in degrees. */
  rotation: number
}
/**
 * A text span at a specific position.
 *
 * Field *values* are derived from the canonical [`pdf_engine::TextSpanInfo`]
 * (the SDK single source of truth) via the `From` impl below, so the Node
 * binding cannot drift from the Tauri/serde wire form in its value logic.
 * (JS key casing follows napi's own camelCase convention.)
 */
export interface TextSpanInfo {
  /** The extracted text. */
  text: string
  /** X position in user space. */
  x: number
  /** Y position in user space. */
  y: number
  /** Span width in user space. */
  width: number
  /** Span height in user space (font-size / ascent extent). */
  height: number
  /** Font size in points. */
  fontSize: number
  /** PostScript font name with subset prefix stripped, if known. */
  fontName?: string
  /** Inferred bold style. */
  isBold: boolean
  /** Inferred italic style. */
  isItalic: boolean
  /** Fill colour as sRGB `[r, g, b]` in 0.0–1.0, if resolved. */
  color?: Array<number>
  /** Width provenance: "Metric" or "Estimate". */
  widthSource: string
  /** Per-glyph bounds `[x0, y0, x1, y1]` (y up), if available. */
  charBounds?: Array<Array<number>>
  /** Full affine transform `[a, b, c, d, e, f]` of the first glyph, if any. */
  transform?: Array<number>
  /** Numeric font weight (~100–900) from embedded font data, if available. */
  fontWeight?: number
  /** Serif flag from embedded font data, if available. */
  isSerif?: boolean
  /** Monospace flag from embedded font data, if available. */
  isMonospace?: boolean
  /** Coarse PDF text render mode: 0 fill, 1 stroke, 3 invisible. */
  renderMode?: number
  /** Vertical font metrics (/1000 em) from the embedded font, if available. */
  fontMetrics?: FontMetricsInfo
}
/** Vertical font metrics returned to JavaScript (values in /1000 em). */
export interface FontMetricsInfo {
  /** Ascent above the baseline. */
  ascent: number
  /** Descent below the baseline (negative). */
  descent: number
  /** Cap height, if present in the font. */
  capHeight?: number
  /** x-height, if present in the font. */
  xHeight?: number
}
/** A block of text (grouped by vertical proximity). */
export interface TextBlockInfo {
  /** Concatenated text of the block. */
  text: string
  /** Individual spans within this block. */
  spans: Array<TextSpanInfo>
}
/** Result of a text redaction operation. */
export interface RedactionResult {
  /** Number of text matches found. */
  matchesFound: number
  /** Number of page areas redacted. */
  areasRedacted: number
  /** Number of pages affected. */
  pagesAffected: number
}
/** Signature validation result. */
export interface SignatureResult {
  /** Validation status: "valid", "invalid", or "unknown". */
  status: string
  /** Reason for invalid/unknown status. */
  reason?: string
  /** Fully qualified field name. */
  fieldName: string
  /** Signer common name, if available. */
  signer?: string
  /** Signing timestamp, if available. */
  timestamp?: string
}
/** PDF/A compliance issue. */
export interface ComplianceIssueInfo {
  /** Rule identifier. */
  rule: string
  /** Severity: "error", "warning", or "info". */
  severity: string
  /** Human-readable description. */
  message: string
}
/** PDF/A compliance report. */
export interface ComplianceReportInfo {
  /** Whether the document is compliant. */
  compliant: boolean
  /** Number of errors. */
  errorCount: number
  /** Number of warnings. */
  warningCount: number
  /** All issues found. */
  issues: Array<ComplianceIssueInfo>
}
/** Information about a single form field. */
export interface FormFieldInfo {
  /** Fully qualified field name (e.g., "form.name"). */
  name: string
  /** Field type: "text", "button", "choice", or "signature". */
  fieldType: string
  /** Current value, if any. */
  value?: string
  /** Whether the field is read-only. */
  readOnly: boolean
}
/**
 * Open a PDF from a file path.
 *
 * Convenience wrapper around `PdfDocument.open` for path-based workflows.
 */
export declare function openPdf(path: string): PdfDocument
/**
 * Merge multiple PDF files into a single output file.
 *
 * Reads each input path, concatenates all pages in order, and writes the
 * result to `output_path`. All input files must be valid, readable PDFs.
 *
 * ```js
 * const { mergePdfs } = require('@pdfluent/node');
 * await mergePdfs(['a.pdf', 'b.pdf'], 'merged.pdf');
 * ```
 */
export declare function mergePdfs(paths: Array<string>, outputPath: string): void
/**
 * Validate a PDF file against a PDF/A conformance level.
 *
 * `level` must be one of: "1a", "1b", "2a", "2b", "2u", "3a", "3b", "3u".
 *
 * Returns a `ComplianceReportInfo` with `compliant`, `errorCount`,
 * `warningCount`, and a list of `issues`.
 *
 * ```js
 * const { validatePdfA } = require('@pdfluent/node');
 * const report = validatePdfA('document.pdf', '2b');
 * console.log(report.compliant, report.errorCount);
 * ```
 */
export declare function validatePdfa(path: string, level: string): ComplianceReportInfo
/**
 * A PDF document handle.
 *
 * Open a document with `PdfDocument.open(buffer)` or
 * `PdfDocument.openAsync(buffer)`.
 */
export declare class PdfDocument {
  /** Open a PDF from a Buffer (synchronous). */
  static open(data: Buffer): PdfDocument
  /** Open a PDF from a Buffer (async — runs on worker thread). */
  static openAsync(data: Buffer): Promise<PdfDocument>
  /** Open a password-protected PDF. */
  static openWithPassword(data: Buffer, password: string): PdfDocument
  /** Number of pages in the document. */
  get pageCount(): number
  /** Get document metadata. */
  info(): DocumentInfo
  /** Get a page handle (0-based index). */
  page(index: number): PdfPage
  /** Render a single page to RGBA pixels (synchronous). */
  renderPage(index: number, options?: RenderOpts | undefined | null): RenderResult
  /** Render a single page to RGBA pixels (async — worker thread). */
  renderPageAsync(index: number, options?: RenderOpts | undefined | null): Promise<RenderResult>
  /** Generate a thumbnail for a page (async). */
  thumbnail(index: number, maxDimension?: number | undefined | null): Promise<RenderResult>
  /** Extract text from a page (synchronous). */
  extractText(index: number): string
  /** Extract text from a page (async — worker thread). */
  extractTextAsync(index: number): Promise<string>
  /** Search for text across all pages. Returns 0-based page indices. */
  searchText(query: string): Array<number>
  /** Get document bookmarks / outline. */
  bookmarks(): Array<BookmarkItem>
  /** Get page geometry (dimensions, rotation). */
  pageGeometry(index: number): PageGeometry
  /** Render all pages in parallel (async). */
  renderAll(options?: RenderOpts | undefined | null): Promise<Array<RenderResult>>
  /** Extract structured text blocks from a page. */
  extractTextBlocks(index: number): Array<TextBlockInfo>
  /** Get all form fields in the document. */
  getFormFields(): Array<FormFieldInfo>
  /**
   * Get all form fields in the document.
   *
   * @deprecated Use {@link getFormFields} instead — the canonical
   * cross-language name (snake_case `get_form_fields` in Rust/Python).
   * Kept for backward compatibility; will be removed in 1.0.0.
   */
  formFields(): Array<FormFieldInfo>
  /** Get the value of a form field by its fully qualified name. */
  getFieldValue(name: string): string | null
  /**
   * Set the value of a form field by its fully qualified name.
   *
   * Routes through [`pdf_forms::apply_field_value`] — the single SDK
   * writeback chain — so `/V` encoding (ASCII literal else UTF-16BE+BOM),
   * per-widget `/AS` sync, and `/AP` regeneration stay consistent, and
   * read-only fields are rejected. The change is persisted to the
   * document — a subsequent `save()` will write the updated value.
   */
  setFormField(name: string, value: string): void
  /**
   * Set the value of a form field by its fully qualified name.
   *
   * @deprecated Use {@link setFormField} instead — the canonical
   * cross-language name (snake_case `set_form_field` in Rust/Python).
   * Kept for backward compatibility; will be removed in 1.0.0.
   */
  setFieldValue(name: string, value: string): void
  /**
   * Set multiple selected values on a multi-select list box.
   *
   * Routes through [`pdf_forms::apply_choice_multi`]: writes `/V` as an
   * array of text strings and rebuilds `/I` (the sorted selected-index
   * cache) to match what Adobe Acrobat produces. Pass an empty array to
   * clear the selection. The field must be a multi-select list box
   * (`/Ff` MultiSelect flag); for non-editable list boxes every value must
   * be one of the field's `/Opt` options.
   */
  setMultiSelect(name: string, values: Array<string>): void
  /** Get annotations on a specific page (0-based index). */
  annotations(pageIndex: number): Array<AnnotationInfo>
  /** Validate all digital signatures in the document. */
  validateSignatures(): Array<SignatureResult>
  /**
   * Save the document to a file path.
   *
   * Writes the current (possibly modified) document to disk. Any changes
   * from `setFormField`, `addAnnotation`, or `redactText` are included.
   */
  save(path: string): void
  /**
   * Add an annotation to a page (0-based index).
   *
   * `annot_type` must be one of: `"highlight"`, `"freetext"`, `"note"`,
   * `"underline"`, `"strikeout"`, `"squiggly"`.
   *
   * `rect` is `[x0, y0, x1, y1]` in PDF user-space coordinates.
   * For `"freetext"`, `content` becomes the visible text.
   */
  addAnnotation(page: number, annotType: string, rect: Array<number>, content?: string | undefined | null): void
  /**
   * Redact all occurrences of `search_term` on a page (0-based index).
   *
   * Pass `page = u32::MAX` (or omit via a wrapper) to redact across all pages.
   * The document is modified in-place; call `save()` to persist.
   *
   * Returns a summary of what was redacted.
   */
  redactText(searchTerm: string, page?: number | undefined | null): RedactionResult
  /**
   * Encrypt the document and write it to `output_path`.
   *
   * Uses AES-256 with `password` as both the user and owner password.
   * The in-memory document is not modified — encryption is applied to a
   * temporary clone and only the written file is encrypted.
   */
  encrypt(outputPath: string, password: string): void
  /**
   * Remove encryption and write the decrypted document to `output_path`.
   *
   * Only useful if the document was opened with `openWithPassword`.
   * After this call the saved file has no password protection.
   */
  decrypt(outputPath: string): void
  /**
   * Validate the document against a PDF/A conformance level.
   *
   * Level is specified as a string: "1a", "1b", "2a", "2b", "2u", "3a", "3b", "3u".
   */
  validatePdfa(level: string): ComplianceReportInfo
  /**
   * Convert the document to a Word `.docx` package.
   *
   * Requires a Business licence or higher. Without one the call throws,
   * and the message points at the free 30-day evaluation key rather than
   * the price list.
   */
  toDocx(): Buffer
  /** Convert the document to an Excel `.xlsx` workbook. See `toDocx`. */
  toXlsx(): Buffer
  /**
   * Convert the document to a PowerPoint `.pptx` deck, one slide per page.
   * See `toDocx`.
   */
  toPptx(): Buffer
}
/** A handle to a single page within a PDF document. */
export declare class PdfPage {
  /** Page index (0-based). */
  get index(): number
  /** Page width in PDF points. */
  get width(): number
  /** Page height in PDF points. */
  get height(): number
  /** Page geometry (dimensions + rotation). */
  geometry(): PageGeometry
  /** Render this page to RGBA pixels (synchronous). */
  render(options?: RenderOpts | undefined | null): RenderResult
  /** Render this page to RGBA pixels (async — worker thread). */
  renderAsync(options?: RenderOpts | undefined | null): Promise<RenderResult>
  /** Generate a thumbnail (async). */
  thumbnail(maxDimension?: number | undefined | null): Promise<RenderResult>
  /** Extract text from this page. */
  text(): string
  /** Extract text from this page (async). */
  textAsync(): Promise<string>
  /** Extract structured text blocks from this page. */
  textBlocks(): Array<TextBlockInfo>
  /** Get annotations on this page. */
  annotations(): Array<AnnotationInfo>
}
/**
 * Find and replace PDF text while preserving fonts, positioning and the
 * surrounding page content.
 */
export declare class TextEditor {
  /** Open a PDF from a Buffer. */
  static open(data: Buffer): TextEditor
  /** Number of pages. */
  pageCount(): number
  /**
   * Find text occurrences. `queryJson` is a JSON object:
   *
   * ```json
   * {
   *   "text": "Acme B.V.",
   *   "caseInsensitive": false,
   *   "pages": [1, 5],
   *   "region": { "page": 1, "rect": [x0, y0, x1, y1], "relation": "intersects" },
   *   "limit": 100
   * }
   * ```
   *
   * Returns a JSON array of matches; each carries an opaque `id` valid
   * until the next applied edit on this document, and an `editable` flag.
   */
  findText(queryJson: string): string
  /**
   * Find and replace in one call. Returns the JSON replacement report.
   *
   * `optionsJson` may be `"{}"`; see the README for the option surface.
   */
  replaceText(queryJson: string, replacement: string, optionsJson: string): string
  /**
   * Apply replacements to matches located earlier with `findText`.
   *
   * `editsJson` is a JSON array of `{"id": "<match id>", "text": "<new>"}`.
   * They commit as one transaction; by default any invalid edit aborts the
   * whole batch and the document stays untouched.
   */
  replaceMatches(editsJson: string, optionsJson: string): string
  /** Serialize the (possibly edited) document to a Buffer. */
  toBuffer(): Buffer
  /** Write the (possibly edited) document to `path`. */
  save(path: string): void
}

// @pdfluent-typed-error-layer
// Hand-maintained typings for the typed-error layer (see typed-error-layer.js).
// `scripts/build/postbuild.cjs` appends this to the napi-generated `index.d.ts`
// after every build. SOURCE OF TRUTH: this file — do not edit the copy inside
// `index.d.ts`.

/**
 * Base class for all PDFluent SDK errors.
 *
 * Always branch on `.code` — never on `.message`.
 */
export declare class PdfluentError extends Error {
  /** Stable machine-readable error code from the C8 error catalogue. */
  readonly code: string | null
  /** Short verb describing the operation that failed (e.g. "activate"). */
  readonly operation: string | null
  /** Optional human-readable detail string. May be `null`. */
  readonly cause: string | null
}

/** License-specific error subclass thrown by all license activation surfaces. */
export declare class PdfluentLicenseError extends PdfluentError {}
