/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS — error classes, structured-error decoder,
   and license wrappers are appended by hand below the auto-generated
   section.  Re-run `napi build --release --platform` to regenerate the
   native bindings; the JS surface customisations live after the require
   block at the bottom of this file. */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

// ── Error hierarchy ───────────────────────────────────────────────────────────

/**
 * Base class for all errors thrown by @pdfluent/node.
 *
 * Always carries a stable, machine-readable `.code` string drawn from the
 * C8 error catalogue (`docs/error_catalogue.md`).  Branch on `.code` —
 * never on `.message`.
 *
 *   - `.code`       — stable identifier (e.g. `"E-LICENSE-INVALID"`)
 *   - `.message`    — short, stable description
 *   - `.operation`  — short verb describing what failed (e.g. `"activate"`)
 *   - `.cause`      — optional underlying detail (may be `null`)
 */
class PdfluentError extends Error {
  constructor(message, opts) {
    super(message)
    this.name = 'PdfluentError'
    this.code = (opts && opts.code) || 'E-OPERATION-FAILED'
    this.operation = (opts && opts.operation) || null
    this.cause = (opts && opts.cause) || null
    if (Error.captureStackTrace) Error.captureStackTrace(this, this.constructor)
  }
}

/** File I/O failure — cannot read, write, or create a PDF file. */
class PdfluentIoError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-IO-GENERIC', ...(opts || {}) })
    this.name = 'PdfluentIoError'
  }
}

/** Corrupt or structurally invalid PDF. */
class PdfluentParseError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-PARSE-INVALID-PDF', ...(opts || {}) })
    this.name = 'PdfluentParseError'
  }
}

/** Wrong or missing password for an encrypted PDF. */
class PdfluentPasswordError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-SECURITY-DECRYPTION-FAILED', ...(opts || {}) })
    this.name = 'PdfluentPasswordError'
  }
}

/** Page index out of range. */
class PdfluentPageError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-OPERATION-FAILED', ...(opts || {}) })
    this.name = 'PdfluentPageError'
  }
}

/** Form operation failed — document has no form, or field not found. */
class PdfluentFormError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-OPERATION-FAILED', ...(opts || {}) })
    this.name = 'PdfluentFormError'
  }
}

/** Runtime operation failure (redact, encrypt, sign, etc.). */
class PdfluentOperationError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-OPERATION-FAILED', ...(opts || {}) })
    this.name = 'PdfluentOperationError'
  }
}

/**
 * License activation, capability, or tier failure.
 *
 * The `.code` is one of:
 *   - `"E-LICENSE-INVALID"`                — key malformed / tier conflict.
 *   - `"E-LICENSE-FEATURE-NOT-IN-TIER"`    — feature requires higher tier.
 *   - `"E-LICENSE-CAPABILITY-NOT-COMPILED"`— feature gated by Cargo flag.
 */
class PdfluentLicenseError extends PdfluentError {
  constructor(message, opts) {
    super(message, { code: 'E-LICENSE-INVALID', ...(opts || {}) })
    this.name = 'PdfluentLicenseError'
  }
}

/**
 * Try to parse a structured JSON error payload emitted by the native layer
 * (see `crates/pdf-node/src/error.rs`).  Returns `null` if `msg` is not a
 * valid structured payload — callers fall back to legacy heuristics.
 */
function _parseStructuredPayload(msg) {
  if (typeof msg !== 'string') return null
  const trimmed = msg.trim()
  if (!trimmed.startsWith('{') || !trimmed.endsWith('}')) return null
  let parsed
  try {
    parsed = JSON.parse(trimmed)
  } catch {
    return null
  }
  if (!parsed || typeof parsed !== 'object') return null
  if (typeof parsed.code !== 'string') return null
  if (typeof parsed.message !== 'string') return null
  return parsed
}

/**
 * Translate a raw NAPI Error into a typed PdfluentError subclass.
 *
 * If the native layer emitted a structured JSON payload (the modern path
 * for license errors and future surfaces), the typed shape is recovered
 * verbatim.  Otherwise the legacy free-text heuristic categorises the
 * error so existing call-sites keep working.
 *
 * License paths NEVER fall through to message-regex heuristics.
 */
function _toPdfluentError(err) {
  const msg = err && err.message ? err.message : String(err)

  const structured = _parseStructuredPayload(msg)
  if (structured) {
    const opts = {
      code: structured.code,
      operation: structured.operation || null,
      cause: structured.cause || null,
    }
    if (structured.code.startsWith('E-LICENSE-')) {
      return new PdfluentLicenseError(structured.message, opts)
    }
    if (structured.code.startsWith('E-IO-')) {
      return new PdfluentIoError(structured.message, opts)
    }
    if (structured.code.startsWith('E-PARSE-')) {
      return new PdfluentParseError(structured.message, opts)
    }
    if (structured.code.startsWith('E-SECURITY-')) {
      return new PdfluentPasswordError(structured.message, opts)
    }
    return new PdfluentError(structured.message, opts)
  }

  // Legacy free-text heuristics — for non-license native call-sites that
  // still emit ad-hoc messages.  License paths NEVER reach this branch.
  if (/cannot read|cannot write|cannot create|cannot save|ENOENT|EACCES/i.test(msg))
    return new PdfluentIoError(msg)
  if (/invalid PDF|parse|corrupt|malformed|unexpected.*PDF/i.test(msg))
    return new PdfluentParseError(msg)
  if (/password|encrypted|decrypt/i.test(msg))
    return new PdfluentPasswordError(msg)
  if (/out of range|page \d+ out of range/i.test(msg))
    return new PdfluentPageError(msg)
  if (/no form|form field|not writable|has no form/i.test(msg))
    return new PdfluentFormError(msg)
  if (/redact|encrypt|sign|merge|annotation|thumbnail/i.test(msg))
    return new PdfluentOperationError(msg)
  return new PdfluentError(msg)
}

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm64.node')
          } else {
            nativeBinding = require('@pdfluent/node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm-eabi.node')
          } else {
            nativeBinding = require('@pdfluent/node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@pdfluent/node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@pdfluent/node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@pdfluent/node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'index.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.darwin-universal.node')
      } else {
        nativeBinding = require('@pdfluent/node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'index.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-x64.node')
          } else {
            nativeBinding = require('@pdfluent/node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-arm64.node')
          } else {
            nativeBinding = require('@pdfluent/node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'index.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.freebsd-x64.node')
      } else {
        nativeBinding = require('@pdfluent/node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-musl.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@pdfluent/node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'index.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@pdfluent/node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const {
  PdfDocument,
  openPdf: _openPdf,
  mergePdfs: _mergePdfs,
  validatePdfa: _validatePdfa,
  activate: _activate,
  setLicenseKey: _setLicenseKey,
  status: _status,
  licenseStatus: _licenseStatus,
  PdfPage,
} = nativeBinding

// Thin wrappers re-throw typed PdfluentError subclasses.  The native layer
// emits a structured JSON payload for license errors so we can branch on
// `err.code` instead of pattern-matching message strings.
function openPdf(path) {
  try { return _openPdf(path) } catch (e) { throw _toPdfluentError(e) }
}
function mergePdfs(paths, outputPath) {
  try { return _mergePdfs(paths, outputPath) } catch (e) { throw _toPdfluentError(e) }
}
function validatePdfa(path, level) {
  try { return _validatePdfa(path, level) } catch (e) { throw _toPdfluentError(e) }
}
function activate(licenseKey) {
  try { return _activate(licenseKey) } catch (e) { throw _toPdfluentError(e) }
}
function setLicenseKey(licenseKey) {
  try { return _setLicenseKey(licenseKey) } catch (e) { throw _toPdfluentError(e) }
}
function status() {
  try { return _status() } catch (e) { throw _toPdfluentError(e) }
}
function licenseStatus() {
  try { return _licenseStatus() } catch (e) { throw _toPdfluentError(e) }
}

module.exports.PdfDocument = PdfDocument
module.exports.PdfPage = PdfPage
module.exports.openPdf = openPdf
module.exports.mergePdfs = mergePdfs
module.exports.validatePdfa = validatePdfa
module.exports.activate = activate
module.exports.setLicenseKey = setLicenseKey
module.exports.status = status
module.exports.licenseStatus = licenseStatus
module.exports.PdfluentError = PdfluentError
module.exports.PdfluentIoError = PdfluentIoError
module.exports.PdfluentParseError = PdfluentParseError
module.exports.PdfluentPasswordError = PdfluentPasswordError
module.exports.PdfluentPageError = PdfluentPageError
module.exports.PdfluentFormError = PdfluentFormError
module.exports.PdfluentOperationError = PdfluentOperationError
module.exports.PdfluentLicenseError = PdfluentLicenseError
