#!/usr/bin/env bash
# Generate an HTML visual regression report with side-by-side comparisons.
#
# Usage:
#   ./scripts/avrt-report.sh [INPUT_DIR] [OUTPUT_FILE]
#
# Defaults:
#   INPUT_DIR:   reports/avrt
#   OUTPUT_FILE: reports/avrt/visual-regression.html

set -euo pipefail

INPUT_DIR="${1:-reports/avrt}"
OUTPUT_FILE="${2:-${INPUT_DIR}/visual-regression.html}"

if [[ ! -f "${INPUT_DIR}/summary.json" ]]; then
    echo "ERROR: No summary.json found in ${INPUT_DIR}"
    echo "Run scripts/run-avrt.sh first."
    exit 1
fi

SUMMARY=$(cat "${INPUT_DIR}/summary.json")
TOTAL=$(echo "$SUMMARY" | python3 -c "import json,sys; print(json.load(sys.stdin)['total'])")
PASSED=$(echo "$SUMMARY" | python3 -c "import json,sys; print(json.load(sys.stdin)['passed'])")
FAILED=$(echo "$SUMMARY" | python3 -c "import json,sys; print(json.load(sys.stdin)['failed'])")
SKIPPED=$(echo "$SUMMARY" | python3 -c "import json,sys; print(json.load(sys.stdin)['skipped'])")
PASS_RATE=$(echo "$SUMMARY" | python3 -c "import json,sys; print(json.load(sys.stdin)['pass_rate'])")
THRESHOLD=$(echo "$SUMMARY" | python3 -c "import json,sys; print(json.load(sys.stdin)['threshold_pct'])")

DATE=$(date -u '+%Y-%m-%d %H:%M UTC')

cat > "$OUTPUT_FILE" <<'HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Visual Regression Report</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 1200px; margin: 2rem auto; padding: 0 1rem; color: #333; }
    h1 { border-bottom: 2px solid #7c3aed; padding-bottom: 0.5rem; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
    .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; text-align: center; }
    .card .value { font-size: 2rem; font-weight: 700; }
    .card .label { font-size: 0.875rem; color: #64748b; margin-top: 0.25rem; }
    .pass { color: #16a34a; }
    .fail { color: #dc2626; }
    .bar { background: #e2e8f0; border-radius: 999px; height: 24px; overflow: hidden; margin: 1rem 0; }
    .bar .fill { height: 100%; border-radius: 999px; background: #16a34a; }
    table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
    th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
    .badge.pass { background: #dcfce7; color: #166534; }
    .badge.fail { background: #fef2f2; color: #991b1b; }
    .comparison { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 0.5rem; margin: 0.5rem 0; }
    .comparison img { max-width: 100%; border: 1px solid #e2e8f0; border-radius: 4px; }
    .comparison .label { text-align: center; font-size: 0.75rem; color: #64748b; }
    details { margin: 0.5rem 0; }
    summary { cursor: pointer; font-weight: 500; }
    footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; font-size: 0.875rem; color: #94a3b8; }
  </style>
</head>
<body>
HEADER

cat >> "$OUTPUT_FILE" <<HTML
  <h1>Visual Regression Report</h1>
  <p>Threshold: <strong>${THRESHOLD}%</strong> | Generated: ${DATE}</p>

  <div class="summary">
    <div class="card"><div class="value">${TOTAL}</div><div class="label">Compared</div></div>
    <div class="card"><div class="value pass">${PASSED}</div><div class="label">Passed</div></div>
    <div class="card"><div class="value fail">${FAILED}</div><div class="label">Failed</div></div>
    <div class="card"><div class="value">${SKIPPED}</div><div class="label">Skipped</div></div>
    <div class="card"><div class="value">${PASS_RATE}%</div><div class="label">Pass Rate</div></div>
  </div>

  <div class="bar">
    <div class="fill" style="width: ${PASS_RATE}%"></div>
  </div>

  <h2>Comparison Results</h2>
  <table>
    <thead><tr><th>File</th><th>Status</th><th>Diff %</th><th>Diff Pixels</th></tr></thead>
    <tbody>
HTML

# Parse results from summary JSON
echo "$SUMMARY" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for r in data.get('results', []):
    status = r.get('status', 'SKIP')
    badge_class = 'pass' if status == 'PASS' else 'fail'
    diff_pct = r.get('diff_pct', '-')
    diff_px = r.get('diff_pixels', '-')
    reason = r.get('reason', '')
    if reason:
        diff_pct = reason
    print(f'<tr><td>{r[\"file\"]}</td><td><span class=\"badge {badge_class}\">{status}</span></td><td>{diff_pct}</td><td>{diff_px}</td></tr>')
" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" <<'HTML'
    </tbody>
  </table>

  <footer>
    <p>Generated by XFA Engine AVRT pipeline.</p>
  </footer>
</body>
</html>
HTML

echo "HTML report generated: ${OUTPUT_FILE}"
