#!/usr/bin/env python3
"""Evaluate a `run_gate_ssim.py` result file against the SSIM regression-gate
thresholds defined in story M4-CI-01 (issue #1315).

Thresholds (configurable via flags):
  - mean-SSIM      >= 0.94
  - fully_correct  >= 35%   (status == "pass" in run_gate_ssim.py)

The script:
  1. Reads the JSON file produced by `run_gate_ssim.py`.
  2. Computes mean-SSIM and the fully_correct ratio across all results.
  3. Renders a Markdown report (for posting as a PR comment).
  4. Exits 0 when both thresholds hold, exit 1 otherwise.

The fully_correct definition matches `run_gate_ssim.py`:
  status == "pass"  (i.e. SSIM >= per-file threshold used by run_gate_ssim.py).

Documents skipped for reasons unrelated to render quality (encrypted /
degenerate / oracle_fault / not_found) are excluded from both the SSIM mean
and the fully_correct ratio so a flaky oracle does not poison the gate.
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

DEFAULT_MEAN_SSIM = 0.94
DEFAULT_FULLY_CORRECT_PCT = 35.0

# Statuses that count toward the gate denominator. Anything else (encrypted,
# degenerate, oracle_fault, xfa_error, not_found, crash-without-ssim) is
# excluded — see docstring.
RENDER_STATUSES = {"pass", "fail"}


def load_results(path: Path) -> list[dict]:
    with open(path) as f:
        data = json.load(f)
    return data.get("results", [])


def evaluate(results: list[dict]) -> dict:
    ssim_scores: list[float] = []
    pass_count = 0
    render_total = 0
    status_counts: dict[str, int] = {}

    for row in results:
        render = row.get("render", {}) or {}
        status = render.get("status", "unknown")
        status_counts[status] = status_counts.get(status, 0) + 1
        if status in RENDER_STATUSES:
            render_total += 1
            if status == "pass":
                pass_count += 1
            ssim = render.get("ssim")
            if isinstance(ssim, (int, float)):
                ssim_scores.append(float(ssim))

    mean_ssim = round(statistics.fmean(ssim_scores), 4) if ssim_scores else None
    fully_correct_pct = (
        round(pass_count / render_total * 100, 2) if render_total else None
    )

    return {
        "total": len(results),
        "render_total": render_total,
        "pass_count": pass_count,
        "ssim_samples": len(ssim_scores),
        "mean_ssim": mean_ssim,
        "fully_correct_pct": fully_correct_pct,
        "status_counts": status_counts,
    }


def render_report(
    summary: dict,
    *,
    mean_ssim_threshold: float,
    fully_correct_threshold: float,
    mean_ssim_ok: bool,
    fully_correct_ok: bool,
    gate_ok: bool,
) -> str:
    lines: list[str] = []
    badge = "✅ PASS" if gate_ok else "❌ FAIL"
    lines.append(f"### SSIM Regression Gate — {badge}")
    lines.append("")
    lines.append(
        "Fast-path 50-PDF subset (M4-CI-01). Thresholds match EVH-BASELINE-04 "
        "(mean-SSIM 0.942 / 54% fully_correct), so a normal PR should stay green."
    )
    lines.append("")
    lines.append("| Metric | Threshold | Result | Status |")
    lines.append("|---|---|---|---|")

    mean_ssim = summary["mean_ssim"]
    fully_pct = summary["fully_correct_pct"]
    mean_ssim_str = f"{mean_ssim:.4f}" if mean_ssim is not None else "n/a"
    fully_pct_str = f"{fully_pct:.2f}%" if fully_pct is not None else "n/a"

    lines.append(
        f"| mean-SSIM | ≥ {mean_ssim_threshold:.3f} | "
        f"{mean_ssim_str} | {'✅' if mean_ssim_ok else '❌'} |"
    )
    lines.append(
        f"| fully_correct | ≥ {fully_correct_threshold:.1f}% | "
        f"{fully_pct_str} | {'✅' if fully_correct_ok else '❌'} |"
    )
    lines.append("")
    lines.append(
        f"Documents: total={summary['total']} · "
        f"rendered={summary['render_total']} · "
        f"ssim_samples={summary['ssim_samples']} · "
        f"pass={summary['pass_count']}"
    )
    sc = summary["status_counts"]
    if sc:
        parts = [f"{k}={v}" for k, v in sorted(sc.items())]
        lines.append("Status breakdown: " + " · ".join(parts))
    lines.append("")
    lines.append(
        "_Generated by `.github/workflows/ssim-gate.yml` "
        "(see issue #1315)._"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--result", required=True, help="run_gate_ssim.py JSON output")
    parser.add_argument(
        "--mean-ssim-threshold",
        type=float,
        default=DEFAULT_MEAN_SSIM,
        help=f"Minimum acceptable mean-SSIM (default {DEFAULT_MEAN_SSIM})",
    )
    parser.add_argument(
        "--fully-correct-threshold",
        type=float,
        default=DEFAULT_FULLY_CORRECT_PCT,
        help=(
            f"Minimum acceptable fully_correct percentage "
            f"(default {DEFAULT_FULLY_CORRECT_PCT})"
        ),
    )
    parser.add_argument("--report", help="Write Markdown report to this path")
    parser.add_argument(
        "--summary-json",
        help="Optional path to write the numeric summary as JSON",
    )
    args = parser.parse_args()

    result_path = Path(args.result)
    if not result_path.exists():
        print(f"ERROR: result file not found: {result_path}", file=sys.stderr)
        return 2

    results = load_results(result_path)
    if not results:
        print(f"ERROR: result file has no entries: {result_path}", file=sys.stderr)
        return 2

    summary = evaluate(results)

    mean_ssim = summary["mean_ssim"]
    fully_pct = summary["fully_correct_pct"]
    mean_ssim_ok = mean_ssim is not None and mean_ssim >= args.mean_ssim_threshold
    fully_correct_ok = (
        fully_pct is not None and fully_pct >= args.fully_correct_threshold
    )
    gate_ok = mean_ssim_ok and fully_correct_ok

    report = render_report(
        summary,
        mean_ssim_threshold=args.mean_ssim_threshold,
        fully_correct_threshold=args.fully_correct_threshold,
        mean_ssim_ok=mean_ssim_ok,
        fully_correct_ok=fully_correct_ok,
        gate_ok=gate_ok,
    )

    if args.report:
        Path(args.report).write_text(report)
    sys.stdout.write(report)

    if args.summary_json:
        Path(args.summary_json).write_text(
            json.dumps(
                {
                    "summary": summary,
                    "thresholds": {
                        "mean_ssim": args.mean_ssim_threshold,
                        "fully_correct_pct": args.fully_correct_threshold,
                    },
                    "checks": {
                        "mean_ssim_ok": mean_ssim_ok,
                        "fully_correct_ok": fully_correct_ok,
                        "gate_ok": gate_ok,
                    },
                },
                indent=2,
            )
            + "\n"
        )

    return 0 if gate_ok else 1


if __name__ == "__main__":
    sys.exit(main())
