#!/usr/bin/env bash
# Generate an HTML conformance report from veraPDF JSON results.
#
# Usage:
#   ./scripts/verapdf-report.sh [INPUT_DIR] [OUTPUT_FILE]
#
# Defaults:
#   INPUT_DIR:   reports/verapdf
#   OUTPUT_FILE: reports/verapdf/conformance.html

set -euo pipefail

INPUT_DIR="${1:-reports/verapdf}"
OUTPUT_FILE="${2:-${INPUT_DIR}/conformance.html}"

if [[ ! -f "${INPUT_DIR}/summary.json" ]]; then
    echo "ERROR: No summary.json found in ${INPUT_DIR}"
    echo "Run scripts/run-verapdf.sh first."
    exit 1
fi

# Read summary
TOTAL=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print(d['total'])")
PASSED=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print(d['passed'])")
FAILED=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print(d['failed'])")
ERRORS=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print(d['errors'])")
PASS_RATE=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print(d['pass_rate'])")
PROFILE=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print(d['profile'])")
FAILED_FILES=$(python3 -c "import json; d=json.load(open('${INPUT_DIR}/summary.json')); print('\n'.join(d.get('failed_files', [])))")

DATE=$(date -u '+%Y-%m-%d %H:%M UTC')

cat > "$OUTPUT_FILE" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>veraPDF Conformance Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #333; }
    h1 { border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
    .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; text-align: center; }
    .card .value { font-size: 2rem; font-weight: 700; }
    .card .label { font-size: 0.875rem; color: #64748b; margin-top: 0.25rem; }
    .pass { color: #16a34a; }
    .fail { color: #dc2626; }
    .error { color: #d97706; }
    .bar { background: #e2e8f0; border-radius: 999px; height: 24px; overflow: hidden; margin: 1rem 0; }
    .bar .fill { height: 100%; border-radius: 999px; transition: width 0.3s; }
    .bar .fill.green { background: #16a34a; }
    .bar .fill.red { background: #dc2626; }
    table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
    th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
    .badge.pass { background: #dcfce7; color: #166534; }
    .badge.fail { background: #fef2f2; color: #991b1b; }
    .badge.err { background: #fef3c7; color: #92400e; }
    footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; font-size: 0.875rem; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>veraPDF Conformance Report</h1>
  <p>Profile: <strong>${PROFILE}</strong> | Generated: ${DATE}</p>

  <div class="summary">
    <div class="card"><div class="value">${TOTAL}</div><div class="label">Total Files</div></div>
    <div class="card"><div class="value pass">${PASSED}</div><div class="label">Passed</div></div>
    <div class="card"><div class="value fail">${FAILED}</div><div class="label">Failed</div></div>
    <div class="card"><div class="value error">${ERRORS}</div><div class="label">Errors</div></div>
    <div class="card"><div class="value">${PASS_RATE}%</div><div class="label">Pass Rate</div></div>
  </div>

  <div class="bar">
    <div class="fill green" style="width: ${PASS_RATE}%"></div>
  </div>

  <h2>Results by File</h2>
  <table>
    <thead><tr><th>File</th><th>Status</th></tr></thead>
    <tbody>
HTML

# List all JSON reports (excluding summary)
for report in "${INPUT_DIR}"/*.json; do
    [[ "$(basename "$report")" == "summary.json" ]] && continue
    filename=$(basename "$report" .json)

    # Determine status from individual report
    if grep -q '"compliant": true\|isCompliant="true"' "$report" 2>/dev/null; then
        status='<span class="badge pass">PASS</span>'
    elif grep -q '"compliant": false\|isCompliant="false"' "$report" 2>/dev/null; then
        status='<span class="badge fail">FAIL</span>'
    else
        status='<span class="badge err">ERROR</span>'
    fi

    echo "      <tr><td>${filename}.pdf</td><td>${status}</td></tr>" >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" <<HTML
    </tbody>
  </table>

  <footer>
    <p>Generated by XFA Engine veraPDF integration. Validated with <a href="https://verapdf.org">veraPDF</a>.</p>
  </footer>
</body>
</html>
HTML

echo "HTML report generated: ${OUTPUT_FILE}"
