[package]
name = "formcalc-interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "FormCalc expression interpreter for XFA dynamic forms."

[dependencies]
xfa-dom-resolver.workspace = true
thiserror.workspace = true
