[package]
name = "pdfluent-jbig2"
version = "0.2.0"
description = "A memory-safe, pure-Rust JBIG2 decoder."
authors = ["Laurenz Stampfl <laurenz.stampfl@gmail.com>"]
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/pdfluent"
homepage = "https://pdfluent.com"
documentation = "https://pdfluent.com/docs"
keywords = ["pdf", "image", "jbig2", "compression", "decoder"]
categories = ["encoding"]

[features]
default = ["std"]
std = []

[dependencies]
hayro-ccitt = { package = "pdfluent-ccitt", path = "../hayro-ccitt", version = "=0.2.0" }

[lints.clippy]
too_many_arguments = "allow"
