// Copyright (c) 2026 Innovation Trigger B.V.
//
// PDFluent is available under two licences, at your option: the GNU AGPLv3, or
// the PDFluent Commercial Licence. See the LICENSE file in this repository --
// that file travels with the copy you received, which a URL does not.

//! Every FormCalc script in `fixtures/formcalc` still parses, and none of them
//! is refused by the expression-depth bound (#303, closing #299's follow-ups).
//!
//! `MAX_DEPTH = 64` in `parser.rs` was sized against these fixtures: the
//! deepest of them measures 10. Until now "the 51 scripts still parse" was a
//! sentence in a benchmark report, checked by hand on one branch and never
//! again. This test is that sentence as code, with three properties a manual
//! run does not have:
//!
//! * **A floor on the count.** `FIXTURE_FLOOR` is the number of fixtures on
//!   the day this was written. A directory that is emptied, moved, or half
//!   deleted fails here by number instead of passing vacuously over zero
//!   files -- the shape of failure that let three other green suites measure
//!   nothing (see `scripts/ci/test_skip_lint.py`).
//! * **A distinguished failure for the depth bound.** A fixture refused with
//!   `ExpressionTooDeep` is reported as such, separately from a syntax error,
//!   because that is the regression this guards: a tightened or miscounted
//!   bound that starts refusing real forms.
//! * **Failures by name.** Every file that does not parse is listed, so a red
//!   run says which fixture broke rather than that one did.
//!
//! The scripts are read straight out of the PDF bytes. The fixtures are
//! generated by `crates/xfa-test-runner/examples/generate_formcalc_fixtures.rs`
//! with the XDP stream stored uncompressed, so a byte search for the
//! `<script contentType="application/x-formcalc">` element is enough and this
//! crate does not need a PDF parser to test itself. If a fixture is ever
//! written with a compressed stream, it fails here as "no FormCalc script
//! found" -- loudly, by name -- rather than being skipped.
//!
//! There are no negative fixtures in this directory. `hostile_deep_call_chain`
//! is hostile to the *evaluator's* call-depth guard (`MAX_CALL_DEPTH`), not
//! to the parser: it is 64 short functions calling each other, and it parses.
//!
//! # The #299 mutation matrix, and which test catches which mutation
//!
//! #299 introduced four mechanisms against deep expressions and proved each
//! by breaking it in isolation. That matrix was run by hand. Re-run on the
//! current parser (each mechanism disabled, `cargo test -p
//! formcalc-interpreter`, file restored from a copy and verified by hash),
//! this is which existing test goes red for which mutation:
//!
//! | mechanism disabled | what goes red |
//! |---|---|
//! | recursion guard: the `MAX_RECURSION` checks in `parse_expr` and `parse_unary` never fire | the lib test binary aborts with a stack overflow (SIGABRT) in the first `depth_bounds` test to recurse deeply -- `nested_parentheses_are_refused_not_overflowed` or whichever runs first in parallel |
//! | construction-time bound in the six chain loops: `built(outer, &[left_depth, self.depth])` in `parse_or` .. `parse_multiplicative` replaced by a plain max | `long_operator_chains_are_refused`, `depth_released_on_return_does_not_compose_past_the_bound` and `a_method_call_is_measured_from_the_expression_base` fail on the `debug_assert` in `parse` ("construction built a tree N deep while believing it was within 64"); then `a_deep_tree_that_then_fails_to_parse_is_still_bounded` overflows the stack on the error path and aborts the binary |
//! | construction-time bound in the accessor tail: the four `built(self.depth, &[])` in `parse_accessor_tail` removed | `long_accessor_chains_are_refused` fails on the same `debug_assert`; then `a_deep_tree_that_then_fails_to_parse_is_still_bounded` (the `a.b.b.b.` shape) overflows and aborts |
//! | post-parse backstop: the `ast_depth` check in `parse` and its `debug_assert` both disabled | **nothing.** All 105 lib tests and every integration test stay green. |
//!
//! Two things follow from that last row and are worth knowing before anyone
//! reads the matrix as "four of four":
//!
//! 1. In a `--release` test build (`nightly.yml` runs one) the `debug_assert`
//!    is compiled out, so for the two construction-time rows the *only* red is
//!    the stack overflow in the error-path test. That test is load-bearing;
//!    it must stay in the suite and off any skip list.
//! 2. The backstop is no longer observable from any input. #299 measured it
//!    red ("3 tests fail as assertions") because construction under-counted
//!    at the time and those tests were refused *by* the backstop. Since the
//!    construction-time bound became exact, no token stream reaches the
//!    `if depth > MAX_DEPTH` branch, and `the_backstop_measures_depth_correctly`
//!    asserts `BACKSTOP_FIRED == 0` -- the opposite direction. The check is
//!    defence in depth that no test can currently distinguish from its
//!    absence. Making it testable means lifting it into a function that a
//!    unit test can hand a synthetic 65-deep tree, which is a `parser.rs`
//!    change and is deferred while PR #1670 is on that file.
//!
//! This file adds none of the four mechanisms' tests; they live in
//! `parser.rs`. It records the mapping so the next person does not have to
//! redo the measurement to know what it still proves.

use std::fs;
use std::path::{Path, PathBuf};

use formcalc_interpreter::error::FormCalcError;
use formcalc_interpreter::lexer::tokenize;
use formcalc_interpreter::parser::parse;

/// Number of fixture PDFs on 2026-09-02. Raise it when fixtures are added;
/// never lower it without saying why in the commit that does.
const FIXTURE_FLOOR: usize = 51;

const SCRIPT_OPEN: &[u8] = b"<script contentType=\"application/x-formcalc\">";
const SCRIPT_CLOSE: &[u8] = b"</script>";
const CDATA_OPEN: &[u8] = b"<![CDATA[";
const CDATA_CLOSE: &[u8] = b"]]>";

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/formcalc")
}

fn find(haystack: &[u8], needle: &[u8], from: usize) -> Option<usize> {
    haystack
        .get(from..)?
        .windows(needle.len())
        .position(|w| w == needle)
        .map(|i| i + from)
}

/// Every FormCalc script element in the file, in document order.
fn extract_scripts(pdf: &[u8]) -> Vec<String> {
    let mut scripts = Vec::new();
    let mut cursor = 0;
    while let Some(open) = find(pdf, SCRIPT_OPEN, cursor) {
        let body_start = open + SCRIPT_OPEN.len();
        let Some(close) = find(pdf, SCRIPT_CLOSE, body_start) else {
            break;
        };
        let mut body = &pdf[body_start..close];
        if body.starts_with(CDATA_OPEN) && body.ends_with(CDATA_CLOSE) {
            body = &body[CDATA_OPEN.len()..body.len() - CDATA_CLOSE.len()];
        }
        scripts.push(String::from_utf8_lossy(body).into_owned());
        cursor = close + SCRIPT_CLOSE.len();
    }
    scripts
}

#[test]
fn every_fixture_script_parses_and_none_hits_the_depth_bound() {
    let dir = fixture_dir();
    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| entry.expect("directory entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "pdf"))
        .collect();
    files.sort();

    assert!(
        files.len() >= FIXTURE_FLOOR,
        "{} holds {} fixture PDFs, fewer than the floor of {FIXTURE_FLOOR}; \
         a fixture was deleted or the directory moved",
        dir.display(),
        files.len()
    );

    let mut failures: Vec<String> = Vec::new();
    let mut scripts_seen = 0usize;

    for path in &files {
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("<non-utf8 name>")
            .to_owned();
        let bytes = fs::read(path).unwrap_or_else(|e| panic!("cannot read {name}: {e}"));
        let scripts = extract_scripts(&bytes);
        if scripts.is_empty() {
            failures.push(format!("{name}: no FormCalc script found in the file"));
            continue;
        }
        for (i, src) in scripts.iter().enumerate() {
            scripts_seen += 1;
            match tokenize(src).and_then(parse) {
                Ok(_) => {}
                Err(FormCalcError::ExpressionTooDeep { max_depth }) => failures.push(format!(
                    "{name} (script {i}): refused by the depth bound (max {max_depth}); \
                     a real form is now too deep for the parser"
                )),
                Err(e) => failures.push(format!("{name} (script {i}): {e}")),
            }
        }
    }

    assert!(
        scripts_seen >= FIXTURE_FLOOR,
        "found {scripts_seen} FormCalc scripts across {} files, fewer than the floor \
         of {FIXTURE_FLOOR}",
        files.len()
    );

    for failure in &failures {
        eprintln!("fixture failed: {failure}");
    }
    assert!(
        failures.is_empty(),
        "{} of {} fixture files failed to parse:\n  {}",
        failures.len(),
        files.len(),
        failures.join("\n  ")
    );
}

/// The extractor itself must not be the thing that quietly passes: a fixture
/// whose script is not where the byte search looks yields no scripts, and the
/// test above turns that into a named failure rather than skipping the file.
#[test]
fn extractor_finds_the_script_and_strips_cdata() {
    let pdf =
        b"junk <script contentType=\"application/x-formcalc\"><![CDATA[\n1 + 1\n]]></script> junk";
    assert_eq!(extract_scripts(pdf), vec!["\n1 + 1\n".to_owned()]);
    assert!(extract_scripts(b"%PDF-1.4 no script here").is_empty());
}
