"""Signed-licence lifecycle tests for the Python binding (SDK 1.1).

Tests the public-key + signed-payload path:
    _native.set_license_public_key(key: bytes) -> None
    _native.set_license_payload(payload_json: str) -> None
    _native.set_license_key(json)               # auto-detects JSON (existing)

Fixtures are static (generated by crates/xfa-license fixture-gen, verified
against the Rust verifier) and shared across language tests to prove
cross-language parity.

The Rust OnceLock means public key and tier are each locked for the process
lifetime.  pytest by default shares one process per test *session*, so this
module uses subprocess isolation to keep signed-payload tests independent
of the enterprise-tier autouse fixture in test_license.py.

Run:
    cd crates/pdf-python
    maturin develop -m Cargo.toml
    pytest tests/test_license_signed_payload.py -v
"""

from __future__ import annotations

import subprocess
import sys
import textwrap

import pytest

# ---------------------------------------------------------------------------
# Skip guard — if the native extension is not built, skip the whole module.
# ---------------------------------------------------------------------------
try:
    from pdfluent._native import (
        PdfluentLicenseError,
        set_license_key,
        set_license_payload,
        set_license_public_key,
    )
    _NATIVE_AVAILABLE = True
except ImportError:
    _NATIVE_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not _NATIVE_AVAILABLE,
    reason="pdfluent native extension not built (run: maturin develop)",
)

# ---------------------------------------------------------------------------
# Cross-language test fixtures
# (generated by /tmp/fixture_gen, verified with /tmp/verify_fixtures)
# ---------------------------------------------------------------------------

PUBLIC_KEY_HEX = (
    "175cd1a23d436d170e74046becf56364b547778f15a350f29bfb776de3a41e05"
)

# Basic-tier, expires year 3000, valid signature.
VALID_PAYLOAD = """\
{
  "licensee": "Test Corp",
  "email": "ci@pdfluent.test",
  "company": "PDFluent CI",
  "tier": "basic",
  "seats": 5,
  "issued_at": 1700000000,
  "expires_at": 32503680000,
  "features": [
    "xfa"
  ],
  "signature": "uSoL4HwHIMBAIhKrvdbLlBiTOczw78z71If/rjfBaiihqSu+jbZasnuWA3pfuJqh9ofKH2ACvZha9J3Ga6YMCw=="
}"""

# Same key, same fields, but expires 2020-01-01.
EXPIRED_PAYLOAD = """\
{
  "licensee": "Test Corp",
  "email": "ci@pdfluent.test",
  "company": "PDFluent CI",
  "tier": "basic",
  "seats": 5,
  "issued_at": 1700000000,
  "expires_at": 1577836800,
  "features": [
    "xfa"
  ],
  "signature": "3xvLjs5CjNf8pOKCPgMGJe+8bsTlc8LNSDYjPzqI1KjmvkSRlwbyL4/frEqlcDpcPfa8+STiMnaXpTM8m6h8Bw=="
}"""

# Signed with a DIFFERENT key — signature will not verify.
WRONG_KEY_PAYLOAD = """\
{
  "licensee": "Test Corp",
  "email": "ci@pdfluent.test",
  "company": "PDFluent CI",
  "tier": "basic",
  "seats": 5,
  "issued_at": 1700000000,
  "expires_at": 32503680000,
  "features": [
    "xfa"
  ],
  "signature": "Xr0pO67Klst4i0r5dzXceCXSJP1B+EWtCBtDT5gDyOdyjhgeev7uEo+x0QPtZko1KGTajHwZj6TZjjm6N4EuAQ=="
}"""


def _pub_key_bytes() -> bytes:
    return bytes.fromhex(PUBLIC_KEY_HEX)


# ---------------------------------------------------------------------------
# Subprocess helper — run a snippet in a fresh Python process to avoid
# OnceLock contamination from other test modules.
# ---------------------------------------------------------------------------

def _run_snippet(snippet: str) -> "subprocess.CompletedProcess[str]":
    """Run *snippet* in a clean interpreter and return the CompletedProcess."""
    return subprocess.run(
        [sys.executable, "-c", textwrap.dedent(snippet)],
        capture_output=True,
        text=True,
    )


# ---------------------------------------------------------------------------
# Tests that must run in isolation (OnceLock process-global state)
# ---------------------------------------------------------------------------


class TestBeforePublicKey:
    """set_license_payload / set_license_key with JSON must fail when no key
    has been configured."""

    def test_set_license_payload_before_key_raises(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_payload, PdfluentLicenseError
            try:
                set_license_payload({VALID_PAYLOAD!r})
                raise AssertionError("expected PdfluentLicenseError")
            except PdfluentLicenseError as e:
                assert e.code == "E-LICENSE-INVALID", f"wrong code: {{e.code}}"
        """)
        assert result.returncode == 0, result.stderr

    def test_set_license_key_json_before_key_raises(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_key, PdfluentLicenseError
            try:
                set_license_key({VALID_PAYLOAD!r})
                raise AssertionError("expected PdfluentLicenseError")
            except PdfluentLicenseError as e:
                assert e.code == "E-LICENSE-INVALID", f"wrong code: {{e.code}}"
        """)
        assert result.returncode == 0, result.stderr


class TestSetPublicKey:
    """set_license_public_key validation and idempotency — run in the module's
    own fresh process so the OnceLock is clean."""

    def test_wrong_length_raises_with_code(self) -> None:
        result = _run_snippet("""
            from pdfluent._native import set_license_public_key, PdfluentLicenseError
            try:
                set_license_public_key(b"tooshort")
                raise AssertionError("expected PdfluentLicenseError")
            except PdfluentLicenseError as e:
                assert e.code == "E-LICENSE-INVALID", f"wrong code: {e.code}"
        """)
        assert result.returncode == 0, result.stderr

    def test_valid_key_succeeds(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key
            key = bytes.fromhex("{PUBLIC_KEY_HEX}")
            set_license_public_key(key)  # must not raise
        """)
        assert result.returncode == 0, result.stderr

    def test_same_key_idempotent(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key
            key = bytes.fromhex("{PUBLIC_KEY_HEX}")
            set_license_public_key(key)
            set_license_public_key(key)  # second call must not raise
        """)
        assert result.returncode == 0, result.stderr


class TestSignedPayloadErrors:
    """Error paths after the public key is configured."""

    def test_expired_payload_raises_with_code(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key, set_license_payload, PdfluentLicenseError
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            try:
                set_license_payload({EXPIRED_PAYLOAD!r})
                raise AssertionError("expected PdfluentLicenseError")
            except PdfluentLicenseError as e:
                assert e.code == "E-LICENSE-EXPIRED", f"wrong code: {{e.code}}"
        """)
        assert result.returncode == 0, result.stderr

    def test_wrong_key_payload_raises_with_code(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key, set_license_payload, PdfluentLicenseError
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            try:
                set_license_payload({WRONG_KEY_PAYLOAD!r})
                raise AssertionError("expected PdfluentLicenseError")
            except PdfluentLicenseError as e:
                assert e.code == "E-LICENSE-INVALID-SIGNATURE", f"wrong code: {{e.code}}"
        """)
        assert result.returncode == 0, result.stderr

    def test_malformed_json_raises_with_code(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key, set_license_payload, PdfluentLicenseError
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            try:
                set_license_payload("{{not valid json")
                raise AssertionError("expected PdfluentLicenseError")
            except PdfluentLicenseError as e:
                assert e.code == "E-LICENSE-INVALID", f"wrong code: {{e.code}}"
        """)
        assert result.returncode == 0, result.stderr


class TestSignedPayloadHappyPath:
    """Successful activation and idempotency."""

    def test_valid_payload_activates_developer_tier(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import (
                set_license_public_key, set_license_payload, native_license_info
            )
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            set_license_payload({VALID_PAYLOAD!r})
            info = native_license_info()
            # xfa-license Basic → pdfluent Developer
            assert info.tier == "developer", f"expected developer, got {{info.tier}}"
            assert info.output_is_marked is False
        """)
        assert result.returncode == 0, result.stderr

    def test_valid_payload_idempotent(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import (
                set_license_public_key, set_license_payload, native_license_info
            )
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            set_license_payload({VALID_PAYLOAD!r})
            set_license_payload({VALID_PAYLOAD!r})  # must not raise
            assert native_license_info().tier == "developer"
        """)
        assert result.returncode == 0, result.stderr

    def test_auto_detect_via_set_license_key(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import (
                set_license_public_key, set_license_key, native_license_info
            )
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            set_license_key({VALID_PAYLOAD!r})   # auto-routes JSON → set_license_payload
            assert native_license_info().tier == "developer"
        """)
        assert result.returncode == 0, result.stderr


class TestErrorCodeAttributes:
    """All errors from set_license_payload carry .code and .message."""

    def test_expired_error_has_code_attribute(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key, set_license_payload, PdfluentLicenseError
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            try:
                set_license_payload({EXPIRED_PAYLOAD!r})
            except PdfluentLicenseError as e:
                assert hasattr(e, "code"), "missing .code"
                assert hasattr(e, "message"), "missing .message"
                assert isinstance(e.code, str)
                assert e.code.startswith("E-LICENSE-")
        """)
        assert result.returncode == 0, result.stderr

    def test_invalid_signature_error_has_code_attribute(self) -> None:
        result = _run_snippet(f"""
            from pdfluent._native import set_license_public_key, set_license_payload, PdfluentLicenseError
            set_license_public_key(bytes.fromhex("{PUBLIC_KEY_HEX}"))
            try:
                set_license_payload({WRONG_KEY_PAYLOAD!r})
            except PdfluentLicenseError as e:
                assert hasattr(e, "code"), "missing .code"
                assert e.code == "E-LICENSE-INVALID-SIGNATURE"
        """)
        assert result.returncode == 0, result.stderr
