/**
 * Signed-licence lifecycle tests for @pdfluent/node (SDK 1.1).
 *
 * Tests the public-key + signed-payload path:
 *   setLicensePublicKey(key: Buffer): void
 *   setLicensePayload(payloadJson: string): void
 *   activate(payloadJson: string): void   // auto-detects JSON
 *
 * Fixtures are static (generated once from xfa-license Rust crate) and
 * verified against the Rust core.  Swapping to a different key in
 * WRONG_KEY_PAYLOAD exercises E-LICENSE-INVALID-SIGNATURE.
 *
 * The Rust OnceLock means tier and public key are each locked for the
 * Node-process lifetime.  Jest runs each test file in its own process
 * by default, giving us a clean slate here.
 *
 * Run:
 *   cd crates/pdf-node
 *   napi build --release --platform
 *   npx jest tests/license_signed_payload.test.js
 */

let mod
try {
  mod = require('../index')
} catch (_) {
  describe.skip('pdf-node signed-payload (native module not built)', () => {
    test('placeholder', () => {})
  })
}

if (mod) {
  const {
    activate,
    setLicenseKey,
    setLicensePublicKey,
    setLicensePayload,
    status,
    PdfluentError,
    PdfluentLicenseError,
  } = mod

  // -------------------------------------------------------------------------
  // Cross-language test fixtures (generated by crates/xfa-license fixture-gen,
  // verified against the Rust verifier).
  // -------------------------------------------------------------------------

  const PUBLIC_KEY_HEX =
    '175cd1a23d436d170e74046becf56364b547778f15a350f29bfb776de3a41e05'

  // Basic-tier, expires year 3000, valid signature.
  const VALID_PAYLOAD = `{
  "licensee": "Test Corp",
  "email": "ci@pdfluent.test",
  "company": "PDFluent CI",
  "tier": "basic",
  "seats": 5,
  "issued_at": 1700000000,
  "expires_at": 32503680000,
  "features": [
    "xfa"
  ],
  "signature": "uSoL4HwHIMBAIhKrvdbLlBiTOczw78z71If/rjfBaiihqSu+jbZasnuWA3pfuJqh9ofKH2ACvZha9J3Ga6YMCw=="
}`

  // Same key, same fields, but expires 2020-01-01 (in the past).
  const EXPIRED_PAYLOAD = `{
  "licensee": "Test Corp",
  "email": "ci@pdfluent.test",
  "company": "PDFluent CI",
  "tier": "basic",
  "seats": 5,
  "issued_at": 1700000000,
  "expires_at": 1577836800,
  "features": [
    "xfa"
  ],
  "signature": "3xvLjs5CjNf8pOKCPgMGJe+8bsTlc8LNSDYjPzqI1KjmvkSRlwbyL4/frEqlcDpcPfa8+STiMnaXpTM8m6h8Bw=="
}`

  // Signed with a DIFFERENT key — signature will not verify.
  const WRONG_KEY_PAYLOAD = `{
  "licensee": "Test Corp",
  "email": "ci@pdfluent.test",
  "company": "PDFluent CI",
  "tier": "basic",
  "seats": 5,
  "issued_at": 1700000000,
  "expires_at": 32503680000,
  "features": [
    "xfa"
  ],
  "signature": "Xr0pO67Klst4i0r5dzXceCXSJP1B+EWtCBtDT5gDyOdyjhgeev7uEo+x0QPtZko1KGTajHwZj6TZjjm6N4EuAQ=="
}`

  function publicKeyBuffer() {
    return Buffer.from(PUBLIC_KEY_HEX, 'hex')
  }

  // -------------------------------------------------------------------------
  // Pre-activation snapshot
  // -------------------------------------------------------------------------
  const BEFORE = status()

  test('status() before any activation is trial/inactive', () => {
    expect(BEFORE.active).toBe(false)
    expect(BEFORE.tier).toBe('trial')
  })

  // -------------------------------------------------------------------------
  // Error paths BEFORE the key is set
  // -------------------------------------------------------------------------

  test('setLicensePayload() before setLicensePublicKey() throws E-LICENSE-INVALID', () => {
    let caught
    try {
      setLicensePayload(VALID_PAYLOAD)
    } catch (e) {
      caught = e
    }
    expect(caught).toBeDefined()
    expect(caught).toBeInstanceOf(PdfluentLicenseError)
    expect(caught.code).toBe('E-LICENSE-INVALID')
  })

  test('activate(json) before setLicensePublicKey() throws E-LICENSE-INVALID', () => {
    let caught
    try {
      activate(VALID_PAYLOAD)
    } catch (e) {
      caught = e
    }
    expect(caught).toBeDefined()
    expect(caught).toBeInstanceOf(PdfluentLicenseError)
    expect(caught.code).toBe('E-LICENSE-INVALID')
  })

  // -------------------------------------------------------------------------
  // setLicensePublicKey
  // -------------------------------------------------------------------------

  test('setLicensePublicKey(wrong length) throws E-LICENSE-INVALID', () => {
    let caught
    try {
      setLicensePublicKey(Buffer.from('deadbeef', 'hex')) // 4 bytes, not 32
    } catch (e) {
      caught = e
    }
    expect(caught).toBeDefined()
    expect(caught).toBeInstanceOf(PdfluentLicenseError)
    expect(caught.code).toBe('E-LICENSE-INVALID')
  })

  test('setLicensePublicKey(valid 32-byte key) returns undefined', () => {
    const result = setLicensePublicKey(publicKeyBuffer())
    expect(result).toBeUndefined()
  })

  test('setLicensePublicKey(same key) is idempotent', () => {
    expect(() => setLicensePublicKey(publicKeyBuffer())).not.toThrow()
  })

  // -------------------------------------------------------------------------
  // Expired payload
  // -------------------------------------------------------------------------

  test('setLicensePayload(expired) throws E-LICENSE-EXPIRED', () => {
    let caught
    try {
      setLicensePayload(EXPIRED_PAYLOAD)
    } catch (e) {
      caught = e
    }
    expect(caught).toBeDefined()
    expect(caught).toBeInstanceOf(PdfluentLicenseError)
    expect(caught.code).toBe('E-LICENSE-EXPIRED')
  })

  // -------------------------------------------------------------------------
  // Wrong-key (invalid signature)
  // -------------------------------------------------------------------------

  test('setLicensePayload(wrong key) throws E-LICENSE-INVALID-SIGNATURE', () => {
    let caught
    try {
      setLicensePayload(WRONG_KEY_PAYLOAD)
    } catch (e) {
      caught = e
    }
    expect(caught).toBeDefined()
    expect(caught).toBeInstanceOf(PdfluentLicenseError)
    expect(caught.code).toBe('E-LICENSE-INVALID-SIGNATURE')
  })

  // -------------------------------------------------------------------------
  // Malformed JSON
  // -------------------------------------------------------------------------

  test('setLicensePayload(malformed JSON) throws E-LICENSE-INVALID', () => {
    let caught
    try {
      setLicensePayload('{not valid json')
    } catch (e) {
      caught = e
    }
    expect(caught).toBeDefined()
    expect(caught).toBeInstanceOf(PdfluentLicenseError)
    expect(caught.code).toBe('E-LICENSE-INVALID')
  })

  // -------------------------------------------------------------------------
  // Happy path — activate valid signed payload
  // -------------------------------------------------------------------------

  test('setLicensePayload(valid) activates developer tier', () => {
    setLicensePayload(VALID_PAYLOAD)
    const s = status()
    // xfa-license Basic → pdfluent Developer
    expect(s.active).toBe(true)
    expect(s.tier).toBe('developer')
    expect(s.outputIsMarked).toBe(false)
  })

  test('setLicensePayload(valid) is idempotent after activation', () => {
    expect(() => setLicensePayload(VALID_PAYLOAD)).not.toThrow()
    expect(status().tier).toBe('developer')
  })

  // -------------------------------------------------------------------------
  // Auto-detect via activate() / setLicenseKey()
  // -------------------------------------------------------------------------

  test('activate(json payload) routes to signed-payload path', () => {
    expect(() => activate(VALID_PAYLOAD)).not.toThrow()
    expect(status().tier).toBe('developer')
  })

  test('setLicenseKey(json payload) routes to signed-payload path', () => {
    expect(() => setLicenseKey(VALID_PAYLOAD)).not.toThrow()
    expect(status().tier).toBe('developer')
  })

  // -------------------------------------------------------------------------
  // Error-instance properties
  // -------------------------------------------------------------------------

  test('PdfluentLicenseError from signed-payload path carries code + operation', () => {
    let caught
    try {
      setLicensePayload(WRONG_KEY_PAYLOAD)
    } catch (e) {
      caught = e
    }
    expect(typeof caught.code).toBe('string')
    expect(caught.code).toBe('E-LICENSE-INVALID-SIGNATURE')
    expect(caught.operation).toBe('setLicensePayload')
    expect(caught instanceof PdfluentError).toBe(true)
  })
}
